<?php
define('PRSTUDIO_UC_TESTING',true);class WP_Error{public $code;public $message;public $data;function __construct($c,$m,$d=[]){$this->code=$c;$this->message=$m;$this->data=$d;}}class PRSTUDIO_UC_Bridge{public static array $calls=[];public static function dispatch($current,array $args,array $meta){self::$calls[]=[$args,$meta];return ['ok'=>true,'args'=>$args,'meta'=>$meta];}}require $argv[1]??__DIR__.'/../prstudio-unified-control/includes/class-prstudio-uc-browser-orchestrator-v3.php';function ok($c,$m){if(!$c){fwrite(STDERR,"FAIL $m\n");exit(1);}}set_error_handler(function($s,$m){throw new ErrorException($m,0,$s);});
$s=PRSTUDIO_UC_Browser_Orchestrator::scope(['browser_required'=>true],['checks'=>['runtime_dom'],'evidence_required'=>['OCR']]);ok($s['browser_required']&&$s['ocr_required'],'scope valid browser/ocr');
try{$s=PRSTUDIO_UC_Browser_Orchestrator::scope(['browser_required'=>'false'],['checks'=>[new stdClass,'runtime_dom'],'evidence_required'=>[new stdClass]]);}catch(Throwable $e){fwrite(STDERR,"FAIL malformed scope threw ".get_class($e)."\n");exit(1);}ok($s['browser_required']===true&&$s['ocr_required']===false,'runtime_dom still requires browser; malformed metadata does not synthesize OCR');
$s=PRSTUDIO_UC_Browser_Orchestrator::scope(['browser_required'=>'false'],[]);ok($s['browser_required']===false,'text false browser_required must not force browser');
PRSTUDIO_UC_Bridge::$calls=[];$r=PRSTUDIO_UC_Browser_Orchestrator::inspect(['target'=>' https://example.test ','evidence_required'=>['ocr']]);ok(($r['meta']['action']??'')==='playwright_screenshot_page'&&($r['args']['url']??'')==='https://example.test'&&($r['args']['ocr']??false)===true,'inspect valid OCR dispatch');
PRSTUDIO_UC_Bridge::$calls=[];$r=PRSTUDIO_UC_Browser_Orchestrator::navigate(['target'=>'https://example.test','wait_until'=>'bogus']);ok(($r['meta']['action']??'')==='playwright_goto'&&($r['args']['wait_until']??'')==='complete','invalid wait mode defaults bounded happy path');
$r=PRSTUDIO_UC_Browser_Orchestrator::navigate(['target'=>'https://example.test','wait_until'=>'DOMCONTENTLOADED']);ok(($r['args']['wait_until']??'')==='domcontentloaded','supported wait alias canonicalized');
try{$r=PRSTUDIO_UC_Browser_Orchestrator::inspect(['target'=>new stdClass]);}catch(Throwable $e){fwrite(STDERR,"FAIL malformed target threw ".get_class($e)."\n");exit(1);}ok($r instanceof WP_Error&&$r->code==='prstudio_browser_target_required','malformed target rejected semantically');
$r=PRSTUDIO_UC_Browser_Orchestrator::navigate(['target'=>'   ']);ok($r instanceof WP_Error,'blank target rejected');
restore_error_handler();echo "PASS browser-orchestrator-v3\n";
