<?php
declare(strict_types=1);
define('PRSTUDIO_UC_TESTING', true);
define('PRSTUDIO_UC_VERSION','1.0.0');
function sanitize_key($value){$value=is_string($value)?$value:'';return strtolower((string)preg_replace('/[^a-z0-9_\-]/','',$value));}
final class PRSTUDIO_UC_Idempotency {public static function canonical_json($value): string {return json_encode($value,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?: '';}}
require dirname(__DIR__) . '/prstudio-unified-control/includes/class-prstudio-uc-verifier.php';
function vt(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
$task=['task_uuid'=>'task-1','action'=>'fill','arguments'=>[]];$tests=[];
$tests['verified strong result remains verified and nonblocking']=static function()use($task){$r=PRSTUDIO_UC_Verifier::browser_result($task,['verified'=>true,'applicationAccepted'=>null,'stepType'=>'fill','verificationStrength'=>'dom_readback']);vt($r['ok']===true&&$r['blocking']===false,'verified evidence classification wrong');};
$tests['transport dispatch without effect is not verified']=static function()use($task){$r=PRSTUDIO_UC_Verifier::browser_result($task,['verified'=>true,'applicationAccepted'=>null,'effectVerified'=>null,'stepType'=>'fill','verificationStrength'=>'transport_or_ui_dispatch']);vt($r['ok']===false&&$r['reason']==='browser_effect_not_verified','transport dispatch was promoted to effect verification');};
$tests['transport dispatch with explicit effect can verify']=static function()use($task){$r=PRSTUDIO_UC_Verifier::browser_result($task,['verified'=>true,'effectVerified'=>true,'stepType'=>'fill','verificationStrength'=>'transport_or_ui_dispatch']);vt($r['ok']===true&&$r['effect_verified']===true,'explicit effect evidence was ignored');};
$tests['explicit negative effect always wins']=static function()use($task){$r=PRSTUDIO_UC_Verifier::browser_result($task,['verified'=>true,'effectVerified'=>false,'stepType'=>'fill','verificationStrength'=>'dom_readback']);vt($r['ok']===false&&$r['reason']==='browser_effect_rejected_or_unverified','negative effect evidence was ignored');};
$tests['connect browser requires a concrete existing Chrome window']=static function(){ $t=['task_uuid'=>'c1','action'=>'playwright_connect_browser','arguments'=>[]];$r=PRSTUDIO_UC_Verifier::browser_result($t,['verified'=>true,'stepType'=>'contract_action','verificationStrength'=>'transport_or_ui_dispatch','executed'=>true,'mode'=>'same_profile_existing_window','hostWindowId'=>42]);vt($r['ok']===true&&$r['verification_strength']==='extension_window_probe','valid Chrome connection was not recognized');};
$tests['connect browser with no window is not ready']=static function(){ $t=['task_uuid'=>'c2','action'=>'playwright_connect_browser','arguments'=>[]];$r=PRSTUDIO_UC_Verifier::browser_result($t,['verified'=>true,'stepType'=>'contract_action','executed'=>true,'mode'=>'same_profile_existing_window','hostWindowId'=>null,'tabs'=>[]]);vt($r['ok']===false&&$r['reason']==='browser_connection_not_proven','empty connection was certified');};
$tests['connect over cdp requires a real attach probe']=static function(){ $t=['task_uuid'=>'c3','action'=>'playwright_connect_over_cdp','arguments'=>[]];$bad=PRSTUDIO_UC_Verifier::browser_result($t,['verified'=>true,'stepType'=>'contract_action','executed'=>true,'hostWindowId'=>42]);vt($bad['ok']===false&&$bad['reason']==='cdp_connection_not_proven','connect_over_cdp succeeded without CDP proof');$good=PRSTUDIO_UC_Verifier::browser_result($t,['verified'=>true,'stepType'=>'contract_action','executed'=>true,'hostWindowId'=>42,'cdpProbe'=>['attached'=>true,'protocolVersion'=>'0.1']]);vt($good['ok']===true,'valid CDP attach proof rejected');};
$tests['new context cannot masquerade as same-window status']=static function(){ $t=['task_uuid'=>'c4','action'=>'playwright_new_context','arguments'=>[]];$r=PRSTUDIO_UC_Verifier::browser_result($t,['verified'=>true,'stepType'=>'contract_action','executed'=>true,'hostWindowId'=>42,'mode'=>'same_profile_existing_window']);vt($r['ok']===false&&$r['reason']==='new_browser_context_not_created','new_context false-success survived');};
$tests['unverified result is evidence degradation not veto']=static function()use($task){$r=PRSTUDIO_UC_Verifier::browser_result($task,['verified'=>false,'stepType'=>'fill']);vt($r['ok']===false&&$r['blocking']===false&&$r['reason']==='browser_result_missing_verified_evidence','unverified evidence became blocking');};
$tests['application rejection changes evidence only']=static function()use($task){$r=PRSTUDIO_UC_Verifier::browser_result($task,['verified'=>true,'applicationAccepted'=>false,'stepType'=>'fill','verificationStrength'=>'dom_readback']);vt($r['ok']===false&&$r['reason']==='browser_application_state_rejected','application evidence was not degraded');};
$tests['required application evidence can remain unverified without blocking']=static function()use($task){$t=$task;$t['arguments']['postcondition']=['required'=>true];$r=PRSTUDIO_UC_Verifier::browser_result($t,['verified'=>true,'applicationAccepted'=>null,'stepType'=>'fill','verificationStrength'=>'dom_readback']);vt($r['ok']===false&&$r['reason']==='browser_application_acceptance_not_observed','required evidence became authorization');};
$tests['malformed acceptance is total and nonblocking']=static function()use($task){foreach([['x'],new stdClass(),2,'maybe'] as $bad){$r=PRSTUDIO_UC_Verifier::browser_result($task,['verified'=>true,'applicationAccepted'=>$bad,'stepType'=>'fill','verificationStrength'=>'dom_readback']);vt($r['ok']===false&&$r['blocking']===false,'malformed evidence became gate');}};
$tests['control receipt executed but unverified is not ok']=static function(){ $r=PRSTUDIO_UC_Verifier::control_receipt('/x','update',['status'=>'completed','executed'=>true,'verified'=>false],[]);vt($r['ok']===false&&$r['degraded']===true&&$r['reason']==='executed_effect_unverified','executed/unverified was still reported successful');};
$tests['control receipt technical nonexecution is not ok']=static function(){ $r=PRSTUDIO_UC_Verifier::control_receipt('/x','update',['status'=>'technical_error','executed'=>false,'verified'=>false],['error'=>'network']);vt($r['ok']===false&&$r['reason']==='execution_not_observed','technical nonexecution was certified');};
$tests['control receipt requires executed and verified']=static function(){ $r=PRSTUDIO_UC_Verifier::control_receipt('/x','update',['status'=>'completed','executed'=>true,'verified'=>true],['effect'=>'observed']);vt($r['ok']===true&&$r['verified']===true,'verified effect was not accepted');};
$pass=0;foreach($tests as $name=>$fn){try{$fn();echo "PASS: $name\n";$pass++;}catch(Throwable $e){fwrite(STDERR,"FAIL: $name :: ".get_class($e)." :: {$e->getMessage()}\n");exit(1);}}echo "PASS: verifier effect truth $pass/".count($tests)."\n";
