<?php
// phpcs:ignore missing_direct_file_access_protection -- direct-access guard IS present on the line below; it uses `&& ! defined('PRSTUDIO_UC_TESTING')` for testability and Plugin Check's static pattern doesn't recognize that compound form.
if ( ! defined( 'ABSPATH' ) && ! defined( 'PRSTUDIO_UC_TESTING' ) ) { exit; }
/* PR STUDIO ONE-GUARD INVARIANT: Anti-Crash is the only mutation guard. Verification/risk/telemetry never block an executable action. */
/**
 * Semantic executor for enterprise Agency actions that are not already owned by
 * a native PR STUDIO backend. It never reports success for an unavailable
 * third-party effect: external effects require a registered provider adapter.
 */
final class PRSTUDIO_UC_Agency_Action_Executor {
	public const VERSION = '1.0.0';
	private const STATE = 'prstudio_agency_semantic_state_v10';
	private const MAX_BATCH = 100;
	private const MAX_SOURCES = 20;
	private const MAX_HTTP_BYTES = 2097152;
	private const ACTIONS = array(
		'bundle_builder','marketplace_catalog_sync','personalized_merchandising','price_competitor_scan','dynamic_pricing_engine','promotion_engine_schedule','multi_currency_price_set',
		'carrier_rate_shopping','rma_process','delivery_tracking_notify','generate_shipping_label','fulfillment_order_route','purchase_order_create','warehouse_stock_sync',
		'invoice_generate','tax_calculate','reconcile_payment_gateway','subscription_billing_manage','chargeback_dispute_handle','accounting_software_sync','currency_rates_update',
		'support_ticket_create_route','chatbot_response_generate','live_chat_handoff','refund_process','review_request_automate','csat_nps_survey_send','loyalty_program_manage','customer_360_lookup',
		'cookie_consent_manage','privacy_policy_update','terms_conditions_generate','gdpr_ccpa_data_request','vendor_contract_manage','ip_trademark_monitor','regulatory_compliance_check',
		'waf_rule_manage','ssl_cert_manage','disaster_recovery_failover','load_test_run',
		'data_warehouse_sync','recommendation_engine_train','recommendation_engine_serve','ab_test_create','ab_test_status','cohort_analysis','churn_prediction','ltv_calculate','attribution_model_report',
		'ad_campaign_create','ad_budget_pacing_adjust','bid_optimize','creative_ab_test','roas_report','retargeting_audience_sync',
		'marketplace_onboarding','affiliate_program_manage','influencer_collab_track','b2b_wholesale_portal_manage','partner_api_integration_config',
		'geo_redirect_config','cross_border_duty_calculate','local_payment_method_enable','market_entry_compliance_check',
		'press_release_distribute','media_monitoring_search','review_platform_monitor','crisis_alert_detect','reputation_score_report',
		'competitor_price_monitor','market_trend_analysis'
	);

	public static function boot(): void {
		add_action( 'prstudio_agency_apply_promotion', array( __CLASS__, 'apply_scheduled_promotion' ), 10, 1 );
		add_action( 'prstudio_agency_send_order_contact', array( __CLASS__, 'send_scheduled_order_contact' ), 10, 3 );
		add_action( 'init', array( __CLASS__, 'enforce_waf_rules' ), 1 );
		add_action( 'init', array( __CLASS__, 'handle_cookie_consent' ), 2 );
		add_action( 'template_redirect', array( __CLASS__, 'apply_ab_tests' ), 0 );
		add_action( 'template_redirect', array( __CLASS__, 'apply_geo_redirect' ), 1 );
		add_action( 'wp_footer', array( __CLASS__, 'render_cookie_consent' ), 100 );
		add_filter( 'woocommerce_product_get_price', array( __CLASS__, 'filter_commerce_price' ), 99, 2 );
		add_filter( 'woocommerce_product_variation_get_price', array( __CLASS__, 'filter_commerce_price' ), 99, 2 );
		add_action( 'woocommerce_checkout_process', array( __CLASS__, 'enforce_wholesale_minimum_order' ), 20 );
	}
	public static function supports( string $action ): bool { return in_array( sanitize_key( $action ), self::ACTIONS, true ); }
	public static function action_names(): array { return self::ACTIONS; }
	public static function external_dependency( string $action ): bool { return in_array( sanitize_key( $action ), array( 'accounting_software_sync','ad_campaign_create','ad_budget_pacing_adjust','bid_optimize','creative_ab_test','retargeting_audience_sync','press_release_distribute','marketplace_catalog_sync','data_warehouse_sync' ), true ); }
	private static function v( array $a, string $k, $d = null ) { return array_key_exists( $k, $a ) ? $a[ $k ] : $d; }
	private static function limit( array $a, int $default = 50, int $max = 100 ): int { return max( 1, min( $max, absint( self::v( $a, 'limit', $default ) ) ) ); }
	private static function state(): array { $v = get_option( self::STATE, array() ); return is_array( $v ) ? $v : array(); }
	private static function save_state( array $state ): bool { update_option( self::STATE, $state, false ); return get_option( self::STATE, array() ) === $state; }
	private static function set_state( string $section, string $key, $value ): bool { $s=self::state();$s[$section]=is_array($s[$section]??null)?$s[$section]:array();$s[$section][$key]=$value;return self::save_state($s); }
	private static function get_state( string $section, string $key = '' ) { $s=self::state();$v=$s[$section]??array();return ''===$key?$v:(is_array($v)?($v[$key]??null):null); }
	private static function read_result( array $data, string $evidence ): array { return array_merge( $data, array( 'status'=>'verified','executed'=>true,'mutated'=>false,'verified'=>true,'evidence'=>$evidence ) ); }
	private static function write_result( array $data, bool $verified, string $evidence ): array {
		return array_merge( $data, array( 'status'=>$verified?'completed':'mutated','executed'=>true,'mutated'=>true,'verified'=>$verified,'degraded'=>!$verified,'blocking'=>false,'evidence'=>$evidence ) );
	}
	private static function require_wc() { return function_exists( 'wc_get_product' ) && function_exists( 'wc_get_order' ) ? true : new WP_Error( 'prstudio_wc_required', 'WooCommerce deve essere installato e attivo per questa azione.', array( 'status'=>503,'dependency'=>'woocommerce' ) ); }
	private static function ids( array $payload, string $key='product_ids' ): array { $raw=(array)self::v($payload,$key,self::v($payload,'ids',array()));if(!$raw&&self::v($payload,'id'))$raw=array(self::v($payload,'id'));return array_slice(array_values(array_unique(array_filter(array_map('absint',$raw)))),0,self::MAX_BATCH); }
	private static function uploads_file( string $name ): array { $u=wp_upload_dir();if(!empty($u['error']))return array('error'=>$u['error']);$dir=trailingslashit($u['basedir']).'prstudio';if(!wp_mkdir_p($dir))return array('error'=>'mkdir_failed');$safe=sanitize_file_name($name);return array('path'=>trailingslashit($dir).$safe,'url'=>trailingslashit($u['baseurl']).$safe); }
	private static function redact_sensitive( $value ) {
		if ( ! is_array( $value ) ) { return $value; }
		$out = array();
		foreach ( $value as $key => $item ) {
			$name = strtolower( (string) $key );
			if ( preg_match( '/(?:password|passwd|secret|token|api[_-]?key|authorization|cookie|session|otp|nonce)/i', $name ) ) {
				$out[ $key ] = '[REDACTED]';
				continue;
			}
			$out[ $key ] = is_array( $item ) ? self::redact_sensitive( $item ) : $item;
		}
		return $out;
	}
	private static function external_provider( string $action, array $payload ) {
		$hook='prstudio_enterprise_provider_execute_'.$action;
		if ( ! has_filter( $hook ) ) { return new WP_Error( 'prstudio_external_provider_required', 'L’azione richiede un provider esterno reale. Registrare l’adapter WordPress per il provider già in uso; nessun falso successo viene restituito.', array( 'status'=>503,'action'=>$action,'adapter_hook'=>$hook,'account_or_session_required'=>true ) ); }
		$result=apply_filters($hook,null,$payload,array('action'=>$action,'suite_version'=>'1.0.0'));
		if(is_wp_error($result))return $result;
		if(!is_array($result))return new WP_Error('prstudio_external_provider_invalid','Il provider ha restituito un payload non valido.',array('status'=>502,'action'=>$action));
		$result=self::redact_sensitive($result);
		if(empty($result['executed']))return new WP_Error('prstudio_external_provider_not_executed','Il provider non ha eseguito l’operazione richiesta.',array('status'=>502,'action'=>$action,'result'=>$result));
		if(empty($result['verified'])){$result['status']='degraded';$result['degraded']=true;$result['blocking']=false;$result['verification_warning']='external_provider_effect_unverified';}
		return $result;
	}
	private static function fetch_sources( array $payload ): array {
		$urls=(array)self::v($payload,'source_urls',self::v($payload,'urls',array()));$urls=array_slice(array_values(array_unique(array_filter(array_map('esc_url_raw',$urls)))),0,self::MAX_SOURCES);
		if(!$urls)return array('error'=>new WP_Error('prstudio_sources_required','source_urls/urls obbligatorio per una ricerca esterna senza API.',array('status'=>400)),'items'=>array());
		$items=[];foreach($urls as $url){$r=wp_safe_remote_get($url,array('timeout'=>8,'redirection'=>3,'limit_response_size'=>self::MAX_HTTP_BYTES,'user-agent'=>'PR-STUDIO/1.0.0'));if(is_wp_error($r)){$items[]=array('url'=>$url,'ok'=>false,'error'=>$r->get_error_code());continue;}$code=wp_remote_retrieve_response_code($r);$body=(string)wp_remote_retrieve_body($r);$items[]=array('url'=>$url,'ok'=>$code>=200&&$code<400,'status'=>$code,'body'=>$body,'bytes'=>strlen($body));}return array('items'=>$items);
	}
	private static function text_from_html( string $html, int $max=50000 ): string { $text=html_entity_decode(wp_strip_all_tags($html),ENT_QUOTES|ENT_HTML5,'UTF-8');$text=preg_replace('/\s+/u',' ',trim($text));return mb_substr((string)$text,0,$max); }
	private static function price_from_html( string $html ): ?float {
		if(preg_match('/["\']price["\']\s*:\s*["\']?([0-9]+(?:[\.,][0-9]{1,2})?)/i',$html,$m))return (float)str_replace(',','.',$m[1]);
		if(preg_match('/(?:€|EUR\s*)\s*([0-9]{1,6}(?:[\.,][0-9]{1,2})?)/i',$html,$m))return (float)str_replace(',','.',$m[1]);
		if(preg_match('/([0-9]{1,6}(?:[\.,][0-9]{1,2})?)\s*(?:€|EUR)/i',$html,$m))return (float)str_replace(',','.',$m[1]);
		return null;
	}
	private static function order( array $payload ) { $ok=self::require_wc();if(is_wp_error($ok))return $ok;$id=absint(self::v($payload,'order_id',self::v($payload,'id',0)));$o=$id?wc_get_order($id):false;return $o?:new WP_Error('prstudio_order_required','order_id valido obbligatorio.',array('status'=>400)); }
	private static function customer_orders( int $user_id, int $limit=200 ): array { if(!function_exists('wc_get_orders'))return array();return wc_get_orders(array('customer_id'=>$user_id,'limit'=>$limit,'orderby'=>'date','order'=>'DESC','status'=>array_keys(wc_get_order_statuses()))); }

	public static function execute( string $action, array $payload, array $meta=array() ) {
		$action=sanitize_key($action);if(!self::supports($action))return new WP_Error('prstudio_agency_semantic_unknown','Azione enterprise non assegnata al semantic executor.',array('status'=>404,'action'=>$action));
		try {
			switch($action){
				case 'bundle_builder': return self::bundle_builder($payload);
				case 'marketplace_catalog_sync': return self::marketplace_sync($payload);
				case 'personalized_merchandising': return self::merchandising($payload);
				case 'price_competitor_scan': case 'competitor_price_monitor': return self::competitor_prices($payload,$action);
				case 'dynamic_pricing_engine': return self::dynamic_pricing($payload);
				case 'promotion_engine_schedule': return self::schedule_promotion($payload);
				case 'multi_currency_price_set': return self::currency_prices($payload);
				case 'carrier_rate_shopping': return self::carrier_rates($payload);
				case 'rma_process': return self::rma($payload);
				case 'delivery_tracking_notify': return self::delivery_notify($payload);
				case 'generate_shipping_label': return self::shipping_label($payload);
				case 'fulfillment_order_route': return self::fulfillment_route($payload);
				case 'purchase_order_create': return self::purchase_order($payload);
				case 'warehouse_stock_sync': return self::warehouse_stock($payload);
				case 'invoice_generate': return self::invoice($payload);
				case 'tax_calculate': return self::tax($payload);
				case 'reconcile_payment_gateway': return self::reconcile_gateway($payload);
				case 'subscription_billing_manage': return self::subscription($payload);
				case 'chargeback_dispute_handle': return self::chargeback($payload);
				case 'accounting_software_sync': return self::external_provider($action,$payload);
				case 'currency_rates_update': return self::currency_rates($payload);
				case 'support_ticket_create_route': return self::support_ticket($payload);
				case 'chatbot_response_generate': return self::chatbot($payload);
				case 'live_chat_handoff': return self::chat_handoff($payload);
				case 'refund_process': return self::refund($payload);
				case 'review_request_automate': return self::email_order_contact($payload,'review');
				case 'csat_nps_survey_send': return self::email_order_contact($payload,'survey');
				case 'loyalty_program_manage': return self::loyalty($payload);
				case 'customer_360_lookup': return self::customer360($payload);
				case 'cookie_consent_manage': return self::cookie_consent($payload);
				case 'privacy_policy_update': return self::policy_page($payload,'privacy');
				case 'terms_conditions_generate': return self::policy_page($payload,'terms');
				case 'gdpr_ccpa_data_request': return self::privacy_request($payload);
				case 'vendor_contract_manage': return self::state_record('vendor_contracts',$payload,'contract_id');
				case 'ip_trademark_monitor': return self::keyword_monitor($payload,'ip_trademark');
				case 'regulatory_compliance_check': return self::compliance($payload);
				case 'waf_rule_manage': return self::waf($payload);
				case 'ssl_cert_manage': return self::ssl($payload);
				case 'disaster_recovery_failover': return self::disaster_recovery($payload);
				case 'load_test_run': return self::load_test($payload);
				case 'data_warehouse_sync': return self::warehouse_export($payload);
				case 'recommendation_engine_train': return self::recommendation_train($payload);
				case 'recommendation_engine_serve': return self::recommendation_serve($payload);
				case 'ab_test_create': return self::ab_create($payload);
				case 'ab_test_status': return self::ab_status($payload);
				case 'cohort_analysis': return self::cohort($payload);
				case 'churn_prediction': return self::churn($payload);
				case 'ltv_calculate': return self::ltv($payload);
				case 'attribution_model_report': return self::attribution($payload);
				case 'ad_campaign_create': case 'ad_budget_pacing_adjust': case 'bid_optimize': case 'creative_ab_test': case 'retargeting_audience_sync': return self::external_provider($action,$payload);
				case 'roas_report': return self::roas($payload);
				case 'marketplace_onboarding': return self::state_record('marketplaces',$payload,'marketplace');
				case 'affiliate_program_manage': return self::state_record('affiliate_programs',$payload,'program_id');
				case 'influencer_collab_track': return self::state_record('influencer_collabs',$payload,'collab_id');
				case 'b2b_wholesale_portal_manage': return self::wholesale($payload);
				case 'partner_api_integration_config': return self::partner_api($payload);
				case 'geo_redirect_config': return self::geo_redirect($payload);
				case 'cross_border_duty_calculate': return self::duty($payload);
				case 'local_payment_method_enable': return self::payment_method($payload);
				case 'market_entry_compliance_check': return self::market_compliance($payload);
				case 'press_release_distribute': return self::press_release($payload);
				case 'media_monitoring_search': return self::keyword_monitor($payload,'media');
				case 'review_platform_monitor': return self::review_monitor($payload);
				case 'crisis_alert_detect': return self::crisis($payload);
				case 'reputation_score_report': return self::reputation($payload);
				case 'market_trend_analysis': return self::market_trends($payload);
			}
		} catch(Throwable $e){return new WP_Error('prstudio_agency_semantic_exception',$e->getMessage(),array('status'=>500,'action'=>$action,'exception'=>get_class($e)));}
		return new WP_Error('prstudio_agency_semantic_route_error','Azione supportata ma priva di branch; difetto di release.',array('status'=>500,'action'=>$action));
	}

	private static function bundle_builder(array $p){$ok=self::require_wc();if(is_wp_error($ok))return $ok;$id=absint(self::v($p,'product_id',self::v($p,'id',0)));$items=self::ids($p,'bundle_product_ids');if(!$id||!wc_get_product($id)||!$items)return new WP_Error('prstudio_bundle_args','product_id e bundle_product_ids validi obbligatori.',array('status'=>400));update_post_meta($id,'_prstudio_bundle_items',$items);update_post_meta($id,'_prstudio_bundle_discount',(float)self::v($p,'discount_percent',0));$after=(array)get_post_meta($id,'_prstudio_bundle_items',true);return self::write_result(array('product_id'=>$id,'bundle_product_ids'=>$after,'discount_percent'=>(float)get_post_meta($id,'_prstudio_bundle_discount',true)),$after===$items,'bundle_meta_readback');}
	private static function marketplace_sync(array $p){
		if ( has_filter( 'prstudio_enterprise_provider_execute_marketplace_catalog_sync' ) ) { return self::external_provider( 'marketplace_catalog_sync', $p ); }
		$mode = sanitize_key( (string) self::v( $p, 'mode', 'sync' ) );
		if ( ! in_array( $mode, array( 'sync', 'export' ), true ) ) { return new WP_Error( 'prstudio_marketplace_mode_invalid', 'mode deve essere sync oppure export.', array( 'status'=>400 ) ); }
		if ( 'sync' === $mode ) { return new WP_Error( 'prstudio_marketplace_provider_required', 'La sincronizzazione verso un marketplace richiede un provider reale già configurato. Usare mode=export solo per produrre un export locale verificato.', array( 'status'=>503, 'action'=>'marketplace_catalog_sync', 'adapter_hook'=>'prstudio_enterprise_provider_execute_marketplace_catalog_sync' ) ); }
		$ok=self::require_wc();if(is_wp_error($ok))return $ok;$ids=self::ids($p);if(!$ids&&function_exists('wc_get_products'))$ids=array_map('absint',wc_get_products(array('limit'=>self::limit($p,100,100),'return'=>'ids','status'=>'publish')));if(!$ids)return new WP_Error('prstudio_marketplace_products_required','Nessun prodotto da esportare.',array('status'=>400));
		$rows=[];foreach($ids as $id){$x=wc_get_product($id);if($x)$rows[]=array('id'=>$id,'sku'=>$x->get_sku(),'name'=>$x->get_name(),'price'=>$x->get_price(),'stock_status'=>$x->get_stock_status(),'permalink'=>get_permalink($id));}
		$f=self::uploads_file('marketplace-catalog-'.gmdate('Ymd-His').'.json');if(isset($f['error']))return new WP_Error('prstudio_marketplace_export_failed',$f['error'],array('status'=>500));$written=file_put_contents($f['path'],wp_json_encode($rows,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX);$hash=false!==$written&&is_file($f['path'])?hash_file('sha256',$f['path']):false;
		return self::write_result(array('mode'=>'export','products'=>count($rows),'path'=>$f['path'],'url'=>$f['url'],'sha256'=>$hash?:null,'external_sync'=>false),(bool)$hash,'marketplace_export_hash');
	}

	private static function merchandising(array $p){$ok=self::require_wc();if(is_wp_error($ok))return $ok;$rows=(array)self::v($p,'products',array());if(!$rows){foreach(self::ids($p) as $id)$rows[]=array('id'=>$id,'menu_order'=>self::v($p,'menu_order',0),'featured'=>self::v($p,'featured',null));}if(!$rows)return new WP_Error('prstudio_merch_targets','products/product_ids obbligatori.',array('status'=>400));$out=[];$all=true;foreach(array_slice($rows,0,self::MAX_BATCH) as $r){$id=absint($r['id']??0);$x=wc_get_product($id);if(!$x){$all=false;$out[]=array('id'=>$id,'verified'=>false);continue;}if(array_key_exists('menu_order',$r))$x->set_menu_order((int)$r['menu_order']);if(array_key_exists('featured',$r)&&null!==$r['featured'])$x->set_featured((bool)$r['featured']);$x->save();$y=wc_get_product($id);$v=$y&&(!array_key_exists('menu_order',$r)||$y->get_menu_order()===(int)$r['menu_order'])&&(!array_key_exists('featured',$r)||null===$r['featured']||$y->get_featured()===(bool)$r['featured']);$all=$all&&$v;$out[]=array('id'=>$id,'verified'=>$v,'menu_order'=>$y?$y->get_menu_order():null,'featured'=>$y?$y->get_featured():null);}return self::write_result(array('items'=>$out,'processed'=>count($out)),$all,'woocommerce_product_readback');}
	private static function competitor_prices(array $p,string $action){$f=self::fetch_sources($p);if(isset($f['error']))return $f['error'];$items=[];foreach($f['items'] as $i){$items[]=array('url'=>$i['url'],'ok'=>$i['ok'],'status'=>$i['status']??0,'price'=>!empty($i['body'])?self::price_from_html($i['body']):null,'title'=>!empty($i['body'])&&preg_match('/<title[^>]*>(.*?)<\/title>/is',$i['body'],$m)?self::text_from_html($m[1],240):null);}$prices=array_values(array_filter(array_column($items,'price'),fn($v)=>null!==$v));return self::read_result(array('action'=>$action,'items'=>$items,'prices_found'=>count($prices),'min'=>$prices?min($prices):null,'max'=>$prices?max($prices):null,'average'=>$prices?array_sum($prices)/count($prices):null),'bounded_public_source_fetch');}
	private static function dynamic_pricing(array $p){$ok=self::require_wc();if(is_wp_error($ok))return $ok;$ids=self::ids($p);if(!$ids)return new WP_Error('prstudio_pricing_targets','product_ids obbligatorio.',array('status'=>400));$pct=(float)self::v($p,'percent',self::v($p,'discount_percent',0));$fixed=self::v($p,'sale_price',null);$out=[];$all=true;foreach($ids as $id){$x=wc_get_product($id);if(!$x){$all=false;continue;}$base=(float)$x->get_regular_price();$sale=null!==$fixed?(float)$fixed:max(0,round($base*(1-$pct/100),wc_get_price_decimals()));$x->set_sale_price((string)$sale);$x->save();$y=wc_get_product($id);$v=$y&&(float)$y->get_sale_price()===$sale;$all=$all&&$v;$out[]=array('id'=>$id,'regular_price'=>$base,'sale_price'=>$y?$y->get_sale_price():null,'verified'=>$v);}return self::write_result(array('items'=>$out),$all,'woocommerce_price_readback');}
	private static function schedule_promotion(array $p){$when=(int)self::v($p,'timestamp',0);if(!$when&&!empty($p['start_at']))$when=strtotime((string)$p['start_at']);if(!$when||$when<=time())return new WP_Error('prstudio_promotion_time','timestamp/start_at futuro obbligatorio.',array('status'=>400));$id='promo-'.substr(wp_generate_uuid4(),0,12);$rule=array('id'=>$id,'payload'=>$p,'timestamp'=>$when,'created_at'=>gmdate(DATE_ATOM));if(!self::set_state('promotions',$id,$rule))return new WP_Error('prstudio_promotion_store_failed','Impossibile salvare promozione.',array('status'=>500));$scheduled=wp_schedule_single_event($when,'prstudio_agency_apply_promotion',array($id),true);if(is_wp_error($scheduled))return $scheduled;$next=wp_next_scheduled('prstudio_agency_apply_promotion',array($id));return self::write_result(array('promotion_id'=>$id,'scheduled_at'=>gmdate(DATE_ATOM,$when),'next_run'=>$next),false!==$next,'wp_cron_readback');}
	public static function apply_scheduled_promotion(string $id): void {$rule=self::get_state('promotions',$id);if(!is_array($rule))return;$res=self::dynamic_pricing((array)($rule['payload']??array()));$rule['result']=is_wp_error($res)?array('error'=>$res->get_error_code(),'message'=>$res->get_error_message()):$res;$rule['ran_at']=gmdate(DATE_ATOM);self::set_state('promotions',$id,$rule);}
	private static function currency_prices(array $p){
		$ok=self::require_wc();if(is_wp_error($ok))return $ok;$id=absint(self::v($p,'product_id',self::v($p,'id',0)));$prices=(array)self::v($p,'prices',array());if(!$id||!wc_get_product($id)||!$prices)return new WP_Error('prstudio_currency_prices_args','product_id e prices obbligatori.',array('status'=>400));
		$clean=[];foreach($prices as $c=>$v){$code=strtoupper(preg_replace('/[^A-Z]/i','',(string)$c));if(strlen($code)===3&&is_numeric($v)&&$v>=0)$clean[$code]=(float)$v;}if(!$clean)return new WP_Error('prstudio_currency_prices_invalid','Nessun prezzo valuta valido.',array('status'=>400));
		update_post_meta($id,'_prstudio_currency_prices',$clean);$after=(array)get_post_meta($id,'_prstudio_currency_prices',true);
		$current=function_exists('get_woocommerce_currency')?strtoupper((string)get_woocommerce_currency()):'';$effective=$current&&array_key_exists($current,$after)?(float)$after[$current]:null;
		return self::write_result(array('product_id'=>$id,'prices'=>$after,'current_currency'=>$current,'effective_current_currency_price'=>$effective,'runtime_filter_active'=>true),$after===$clean,'product_meta_and_runtime_price_filter');
	}

	public static function filter_commerce_price( $price, $product ) {
		if ( ! is_object( $product ) || ! method_exists( $product, 'get_id' ) ) { return $price; }
		$numeric = is_numeric( $price ) ? (float) $price : $price;
		$currency = function_exists( 'get_woocommerce_currency' ) ? strtoupper( (string) get_woocommerce_currency() ) : '';
		$map = (array) get_post_meta( (int) $product->get_id(), '_prstudio_currency_prices', true );
		if ( $currency && array_key_exists( $currency, $map ) && is_numeric( $map[ $currency ] ) ) { $numeric = (float) $map[ $currency ]; }
		$wholesale = self::get_state( 'commerce', 'wholesale' );
		if ( is_array( $wholesale ) && ! empty( $wholesale['enabled'] ) && is_user_logged_in() ) {
			$user = wp_get_current_user();
			if ( in_array( 'wholesale_customer', (array) $user->roles, true ) ) { $discount = max( 0.0, min( 100.0, (float) ( $wholesale['discount_percent'] ?? 0 ) ) ); if ( is_numeric( $numeric ) ) { $numeric = round( (float) $numeric * ( 1 - $discount / 100 ), function_exists( 'wc_get_price_decimals' ) ? wc_get_price_decimals() : 2 ); } }
		}
		return $numeric;
	}

	public static function enforce_wholesale_minimum_order(): void {
		$cfg = self::get_state( 'commerce', 'wholesale' ); if ( ! is_array( $cfg ) || empty( $cfg['enabled'] ) || empty( $cfg['minimum_order'] ) || ! is_user_logged_in() || ! function_exists( 'WC' ) || ! WC()->cart ) { return; }
		$user = wp_get_current_user(); if ( ! in_array( 'wholesale_customer', (array) $user->roles, true ) ) { return; }
		$minimum = (float) $cfg['minimum_order']; $subtotal = (float) WC()->cart->get_subtotal(); if ( $subtotal + 0.00001 < $minimum && function_exists( 'wc_add_notice' ) ) { wc_add_notice( sprintf( 'Ordine minimo wholesale: %s', function_exists( 'wc_price' ) ? wp_strip_all_tags( wc_price( $minimum ) ) : (string) $minimum ), 'error' ); }
	}

	private static function carrier_rates(array $p){$rates=(array)self::v($p,'rates',array());if(!$rates&&has_filter('prstudio_enterprise_provider_execute_carrier_rate_shopping'))return self::external_provider('carrier_rate_shopping',$p);if(!$rates)return new WP_Error('prstudio_carrier_rates_required','Fornire rates oppure registrare un carrier provider adapter.',array('status'=>400));$rows=[];foreach($rates as $r)if(is_array($r)&&isset($r['amount']))$rows[]=array('carrier'=>sanitize_text_field((string)($r['carrier']??'')),'service'=>sanitize_text_field((string)($r['service']??'')),'amount'=>(float)$r['amount'],'currency'=>strtoupper(sanitize_text_field((string)($r['currency']??get_woocommerce_currency()))),'eta_days'=>isset($r['eta_days'])?absint($r['eta_days']):null);usort($rows,fn($a,$b)=>$a['amount']<=>$b['amount']);return self::read_result(array('rates'=>$rows,'best'=>$rows[0]??null),'carrier_rate_comparison');}
	private static function rma(array $p){$o=self::order($p);if(is_wp_error($o))return $o;$mode=sanitize_key((string)self::v($p,'mode','create'));$rma=(array)$o->get_meta('_prstudio_rma',true);if('get'===$mode)return self::read_result(array('order_id'=>$o->get_id(),'rma'=>$rma),'order_meta');$rma=array_replace($rma,array('status'=>sanitize_key((string)self::v($p,'status','requested')),'reason'=>sanitize_textarea_field((string)self::v($p,'reason','')),'items'=>(array)self::v($p,'items',array()),'updated_at'=>gmdate(DATE_ATOM)));$o->update_meta_data('_prstudio_rma',$rma);$o->save();$after=(array)wc_get_order($o->get_id())->get_meta('_prstudio_rma',true);return self::write_result(array('order_id'=>$o->get_id(),'rma'=>$after),$after==$rma,'order_rma_readback');}
	private static function delivery_notify(array $p){$o=self::order($p);if(is_wp_error($o))return $o;$to=sanitize_email((string)self::v($p,'email',$o->get_billing_email()));if(!$to)return new WP_Error('prstudio_delivery_email','Email destinatario non disponibile.',array('status'=>400));$tracking=sanitize_text_field((string)self::v($p,'tracking_number',$o->get_meta('_tracking_number',true)));$subject=sanitize_text_field((string)self::v($p,'subject','Aggiornamento consegna ordine #'.$o->get_order_number()));$msg=sanitize_textarea_field((string)self::v($p,'message','Il tuo ordine è in aggiornamento.'.($tracking?' Tracking: '.$tracking:'')));$sent=wp_mail($to,$subject,$msg);if($sent)$o->add_order_note('PR STUDIO: notifica consegna inviata a '.$to);return self::write_result(array('order_id'=>$o->get_id(),'recipient'=>$to,'sent'=>(bool)$sent),(bool)$sent,'wp_mail_result');}
	private static function shipping_label(array $p){$o=self::order($p);if(is_wp_error($o))return $o;$address=$o->get_formatted_shipping_address()?:$o->get_formatted_billing_address();$tracking=esc_html((string)self::v($p,'tracking_number',''));$html='<!doctype html><meta charset="utf-8"><title>Shipping label</title><h1>Ordine #'.esc_html($o->get_order_number()).'</h1><div>'.$address.'</div>'.($tracking?'<p>Tracking: '.$tracking.'</p>':'');$f=self::uploads_file('shipping-label-order-'.$o->get_id().'.html');if(isset($f['error']))return new WP_Error('prstudio_label_path',$f['error'],array('status'=>500));$bytes=file_put_contents($f['path'],$html,LOCK_EX);$hash=false!==$bytes&&is_file($f['path'])?hash_file('sha256',$f['path']):false;return self::write_result(array('order_id'=>$o->get_id(),'path'=>$f['path'],'url'=>$f['url'],'format'=>'html_printable','bytes'=>false!==$bytes?(int)$bytes:0,'sha256'=>$hash?:null,'carrier_postage_purchased'=>false),(bool)$hash,'label_file_sha256');}
	private static function fulfillment_route(array $p){$o=self::order($p);if(is_wp_error($o))return $o;$route=sanitize_text_field((string)self::v($p,'route',self::v($p,'warehouse','')));if(!$route)return new WP_Error('prstudio_fulfillment_route_required','route/warehouse obbligatorio.',array('status'=>400));$o->update_meta_data('_prstudio_fulfillment_route',$route);$o->save();$after=(string)wc_get_order($o->get_id())->get_meta('_prstudio_fulfillment_route',true);return self::write_result(array('order_id'=>$o->get_id(),'route'=>$after),$after===$route,'order_route_readback');}
	private static function purchase_order(array $p){$id=sanitize_key((string)self::v($p,'po_id',''));if(!$id)$id='po-'.gmdate('YmdHis').'-'.wp_rand(100,999);$record=array('id'=>$id,'vendor'=>sanitize_text_field((string)self::v($p,'vendor','')),'items'=>array_slice((array)self::v($p,'items',array()),0,self::MAX_BATCH),'currency'=>strtoupper(sanitize_text_field((string)self::v($p,'currency',function_exists('get_woocommerce_currency')?get_woocommerce_currency():'EUR'))),'status'=>sanitize_key((string)self::v($p,'status','draft')),'updated_at'=>gmdate(DATE_ATOM));$ok=self::set_state('purchase_orders',$id,$record);return self::write_result(array('purchase_order'=>$record),$ok&&self::get_state('purchase_orders',$id)===$record,'state_readback');}
	private static function warehouse_stock(array $p){$ok=self::require_wc();if(is_wp_error($ok))return $ok;$rows=(array)self::v($p,'items',self::v($p,'stock',array()));if(!$rows)return new WP_Error('prstudio_stock_rows','items/stock obbligatorio.',array('status'=>400));$out=[];$all=true;foreach(array_slice($rows,0,self::MAX_BATCH) as $r){if(!is_array($r))continue;$id=absint($r['product_id']??$r['id']??0);$qty=isset($r['quantity'])?(float)$r['quantity']:null;$x=wc_get_product($id);if(!$x||null===$qty){$all=false;continue;}$x->set_manage_stock(true);$x->set_stock_quantity($qty);$x->save();$y=wc_get_product($id);$v=$y&&(float)$y->get_stock_quantity()===$qty;$all=$all&&$v;$out[]=array('product_id'=>$id,'quantity'=>$y?$y->get_stock_quantity():null,'verified'=>$v);}return self::write_result(array('items'=>$out),$all&&count($out)>0,'stock_readback');}
	private static function invoice(array $p){$o=self::order($p);if(is_wp_error($o))return $o;$rows='';foreach($o->get_items() as $item){$rows.='<tr><td>'.esc_html($item->get_name()).'</td><td>'.esc_html((string)$item->get_quantity()).'</td><td>'.wp_kses_post(wc_price($o->get_line_total($item),array('currency'=>$o->get_currency()))).'</td></tr>';}$html='<!doctype html><meta charset="utf-8"><title>Invoice '.$o->get_order_number().'</title><h1>Invoice #'.esc_html($o->get_order_number()).'</h1><p>'.wp_kses_post($o->get_formatted_billing_address()).'</p><table><tr><th>Item</th><th>Qty</th><th>Total</th></tr>'.$rows.'</table><p>Total: '.wp_kses_post($o->get_formatted_order_total()).'</p>';$f=self::uploads_file('invoice-order-'.$o->get_id().'.html');if(isset($f['error']))return new WP_Error('prstudio_invoice_path',$f['error'],array('status'=>500));$bytes=file_put_contents($f['path'],$html,LOCK_EX);$hash=false!==$bytes&&is_file($f['path'])?hash_file('sha256',$f['path']):false;return self::write_result(array('order_id'=>$o->get_id(),'path'=>$f['path'],'url'=>$f['url'],'format'=>'html_printable','bytes'=>false!==$bytes?(int)$bytes:0,'sha256'=>$hash?:null),(bool)$hash,'invoice_file_sha256');}
	private static function tax(array $p){if(!class_exists('WC_Tax'))return new WP_Error('prstudio_wc_tax_required','WC_Tax non disponibile.',array('status'=>503));$price=(float)self::v($p,'amount',self::v($p,'price',0));$class=sanitize_text_field((string)self::v($p,'tax_class',''));$rates=WC_Tax::get_rates($class);$taxes=WC_Tax::calc_tax($price,$rates,(bool)self::v($p,'price_includes_tax',false));return self::read_result(array('amount'=>$price,'tax_class'=>$class,'rates'=>$rates,'taxes'=>$taxes,'tax_total'=>array_sum($taxes)),'woocommerce_tax_engine');}
	private static function reconcile_gateway(array $p){$ok=self::require_wc();if(is_wp_error($ok))return $ok;$rows=(array)self::v($p,'transactions',array());if(!$rows)return new WP_Error('prstudio_transactions_required','transactions obbligatorio.',array('status'=>400));$out=[];$mismatch=0;foreach(array_slice($rows,0,self::MAX_BATCH) as $r){if(!is_array($r))continue;$order=wc_get_order(absint($r['order_id']??0));if(!$order){$mismatch++;$out[]=array('order_id'=>$r['order_id']??0,'match'=>false,'reason'=>'order_not_found');continue;}$match=( !isset($r['transaction_id'])||(string)$order->get_transaction_id()===(string)$r['transaction_id'])&&(!isset($r['amount'])||abs((float)$order->get_total()-(float)$r['amount'])<0.01);if(!$match)$mismatch++;$out[]=array('order_id'=>$order->get_id(),'transaction_id'=>$order->get_transaction_id(),'order_total'=>(float)$order->get_total(),'gateway_amount'=>isset($r['amount'])?(float)$r['amount']:null,'match'=>$match);}return self::read_result(array('items'=>$out,'mismatches'=>$mismatch,'matched'=>count($out)-$mismatch),'gateway_reconciliation');}
	private static function subscription(array $p){if(!function_exists('wcs_get_subscription'))return new WP_Error('prstudio_subscriptions_required','WooCommerce Subscriptions non disponibile.',array('status'=>503,'dependency'=>'woocommerce-subscriptions'));$id=absint(self::v($p,'subscription_id',self::v($p,'id',0)));$s=wcs_get_subscription($id);if(!$s)return new WP_Error('prstudio_subscription_not_found','Subscription non trovata.',array('status'=>404));$mode=sanitize_key((string)self::v($p,'mode','get'));if('get'===$mode)return self::read_result(array('id'=>$id,'status'=>$s->get_status(),'dates'=>$s->get_dates()),'subscription_read');if(in_array($mode,array('active','on-hold','cancelled','pending-cancel'),true)){$s->update_status($mode,'PR STUDIO enterprise action');$after=wcs_get_subscription($id);return self::write_result(array('id'=>$id,'status'=>$after->get_status()),$after->get_status()===$mode,'subscription_status_readback');}return new WP_Error('prstudio_subscription_mode','mode non supportato.',array('status'=>400));}
	private static function chargeback(array $p){$o=self::order($p);if(is_wp_error($o))return $o;$submit=(bool)self::v($p,'submit_external',false);if($submit&&!has_filter('prstudio_enterprise_provider_execute_chargeback_dispute_handle'))return new WP_Error('prstudio_chargeback_provider_required','L’invio della contestazione al gateway richiede un provider reale. Senza submit_external viene gestito soltanto il fascicolo locale verificato.',array('status'=>503,'adapter_hook'=>'prstudio_enterprise_provider_execute_chargeback_dispute_handle'));$record=array('status'=>sanitize_key((string)self::v($p,'status','open')),'reference'=>sanitize_text_field((string)self::v($p,'reference','')),'reason'=>sanitize_textarea_field((string)self::v($p,'reason','')),'external_submitted'=>false,'updated_at'=>gmdate(DATE_ATOM));$o->update_meta_data('_prstudio_chargeback',$record);$o->add_order_note('PR STUDIO chargeback: '.$record['status'].' '.$record['reference']);$o->save();$after=(array)wc_get_order($o->get_id())->get_meta('_prstudio_chargeback',true);if($after!=$record)return self::write_result(array('order_id'=>$o->get_id(),'chargeback'=>$after),false,'chargeback_readback');if($submit){$ext=self::external_provider('chargeback_dispute_handle',array_merge($p,array('order_id'=>$o->get_id(),'local_record'=>$after)));if(is_wp_error($ext))return $ext;$record['external_submitted']=true;$record['external_verified']=true;$record['external_result']=self::redact_sensitive($ext);$o=wc_get_order($o->get_id());$o->update_meta_data('_prstudio_chargeback',$record);$o->save();$after=(array)wc_get_order($o->get_id())->get_meta('_prstudio_chargeback',true);return self::write_result(array('order_id'=>$o->get_id(),'chargeback'=>$after),!empty($after['external_submitted'])&&!empty($after['external_verified']),'chargeback_provider_and_readback');}return self::write_result(array('order_id'=>$o->get_id(),'chargeback'=>$after,'external_submitted'=>false),true,'chargeback_local_readback');}
	private static function currency_rates(array $p){$rates=(array)self::v($p,'rates',array());if(!$rates)return new WP_Error('prstudio_currency_rates_required','rates obbligatorio; PR STUDIO non inventa tassi di cambio.',array('status'=>400));$clean=[];foreach($rates as $c=>$v){$code=strtoupper(preg_replace('/[^A-Z]/i','',(string)$c));if(strlen($code)===3&&is_numeric($v)&&$v>0)$clean[$code]=(float)$v;}if(!$clean)return new WP_Error('prstudio_currency_rates_invalid','Nessun tasso valido.',array('status'=>400));$record=array('base'=>strtoupper(sanitize_text_field((string)self::v($p,'base','EUR'))),'rates'=>$clean,'as_of'=>sanitize_text_field((string)self::v($p,'as_of',gmdate(DATE_ATOM))));$ok=self::set_state('finance','currency_rates',$record);return self::write_result($record,$ok&&self::get_state('finance','currency_rates')===$record,'currency_rate_readback');}
	private static function support_ticket(array $p){$id=sanitize_key((string)self::v($p,'ticket_id',''));if(!$id)$id='ticket-'.substr(wp_generate_uuid4(),0,12);$record=array('id'=>$id,'subject'=>sanitize_text_field((string)self::v($p,'subject','')),'message'=>sanitize_textarea_field((string)self::v($p,'message','')),'customer_id'=>absint(self::v($p,'customer_id',0)),'order_id'=>absint(self::v($p,'order_id',0)),'priority'=>sanitize_key((string)self::v($p,'priority','normal')),'status'=>sanitize_key((string)self::v($p,'status','open')),'route'=>sanitize_key((string)self::v($p,'route','support')),'updated_at'=>gmdate(DATE_ATOM));$ok=self::set_state('support_tickets',$id,$record);return self::write_result(array('ticket'=>$record),$ok&&self::get_state('support_tickets',$id)===$record,'ticket_state_readback');}
	private static function chatbot(array $p){$q=sanitize_text_field((string)self::v($p,'query',self::v($p,'message','')));if(!$q)return new WP_Error('prstudio_chatbot_query','query/message obbligatorio.',array('status'=>400));$posts=get_posts(array('post_type'=>'any','post_status'=>'publish','s'=>$q,'posts_per_page'=>self::limit($p,5,20)));$sources=[];foreach($posts as $post)$sources[]=array('post_id'=>$post->ID,'title'=>$post->post_title,'url'=>get_permalink($post),'excerpt'=>wp_trim_words(wp_strip_all_tags($post->post_content),50));$answer=$sources?('Risultati locali pertinenti: '.implode('; ',array_map(fn($x)=>$x['title'],$sources))):'Nessun contenuto locale corrispondente trovato.';return self::read_result(array('query'=>$q,'answer'=>$answer,'sources'=>$sources,'generation'=>'deterministic_local_search'),'local_content_search');}
	private static function chat_handoff(array $p){
		if ( has_filter( 'prstudio_enterprise_provider_execute_live_chat_handoff' ) ) { return self::external_provider( 'live_chat_handoff', $p ); }
		$id='handoff-'.substr(wp_generate_uuid4(),0,12);$record=array('id'=>$id,'customer_id'=>absint(self::v($p,'customer_id',0)),'channel'=>sanitize_key((string)self::v($p,'channel','manual')),'target'=>sanitize_text_field((string)self::v($p,'target','support')),'context'=>sanitize_textarea_field((string)self::v($p,'context','')),'status'=>'queued','created_at'=>gmdate(DATE_ATOM));$ok=self::set_state('chat_handoffs',$id,$record);
		$notify = sanitize_email( (string) self::v( $p, 'notify_email', get_option( 'admin_email' ) ) ); $sent = $notify ? wp_mail( $notify, 'PR STUDIO live chat handoff '.$id, $record['target']."\n".$record['context'] ) : false;
		$record['notification_sent']=(bool)$sent;$record['notification_email']=$notify;$record['delivery']='local_queue_and_email';self::set_state('chat_handoffs',$id,$record);
		return self::write_result(array('handoff'=>$record),$ok&&self::get_state('chat_handoffs',$id)===$record&&($notify?(bool)$sent:true),'handoff_state_and_notification');
	}

	private static function refund(array $p){$o=self::order($p);if(is_wp_error($o))return $o;if(!function_exists('wc_create_refund'))return new WP_Error('prstudio_wc_refund_required','wc_create_refund non disponibile.',array('status'=>503));$amount=(float)self::v($p,'amount',$o->get_remaining_refund_amount());if($amount<=0)return new WP_Error('prstudio_refund_amount','amount deve essere > 0.',array('status'=>400));$refund=wc_create_refund(array('order_id'=>$o->get_id(),'amount'=>$amount,'reason'=>sanitize_text_field((string)self::v($p,'reason','PR STUDIO refund')),'refund_payment'=>(bool)self::v($p,'refund_payment',false),'restock_items'=>(bool)self::v($p,'restock_items',false)));if(is_wp_error($refund))return $refund;$loaded=wc_get_order($refund->get_id());return self::write_result(array('order_id'=>$o->get_id(),'refund_id'=>$refund->get_id(),'amount'=>(float)$refund->get_amount()),(bool)$loaded,'refund_order_readback');}
	private static function email_order_contact(array $p,string $type){
		$o=self::order($p);if(is_wp_error($o))return $o;
		$send_at=(int)self::v($p,'send_at',0);if(!$send_at&&!empty($p['send_at_iso']))$send_at=(int)strtotime((string)$p['send_at_iso']);
		if($send_at>time()+30&&empty($p['_scheduled_execution'])){ $payload=$p;$payload['_scheduled_execution']=true;$event=wp_schedule_single_event($send_at,'prstudio_agency_send_order_contact',array($o->get_id(),$type,$payload),true);if(is_wp_error($event))return $event;$next=wp_next_scheduled('prstudio_agency_send_order_contact',array($o->get_id(),$type,$payload));return self::write_result(array('order_id'=>$o->get_id(),'kind'=>$type,'scheduled_at'=>gmdate(DATE_ATOM,$send_at),'next_run'=>$next),false!==$next,'wp_cron_readback'); }
		$to=sanitize_email((string)self::v($p,'email',$o->get_billing_email()));if(!$to)return new WP_Error('prstudio_contact_email','Email non disponibile.',array('status'=>400));$subject=sanitize_text_field((string)self::v($p,'subject',$type==='review'?'Come valuti il tuo ordine?':'Questionario soddisfazione'));$url=esc_url_raw((string)self::v($p,'url',''));$body=sanitize_textarea_field((string)self::v($p,'message',$type==='review'?'Grazie per il tuo acquisto. Lascia una recensione.':'Ci aiuti con un breve feedback?'));if($url)$body.="\n".$url;$sent=wp_mail($to,$subject,$body);if($sent){$o->add_order_note('PR STUDIO: '.$type.' request inviata a '.$to);}return self::write_result(array('order_id'=>$o->get_id(),'recipient'=>$to,'kind'=>$type,'sent'=>$sent),(bool)$sent,'wp_mail_result');
	}

	public static function send_scheduled_order_contact( int $order_id, string $type, array $payload ): void {
		$payload['order_id']=$order_id;$payload['_scheduled_execution']=true;$result=self::email_order_contact($payload,sanitize_key($type));
		if(is_wp_error($result)){ error_log('PR STUDIO scheduled contact failed: '.$result->get_error_code().' '.$result->get_error_message()); }
	}

	private static function loyalty(array $p){$uid=absint(self::v($p,'user_id',0));if(!$uid||!get_user_by('id',$uid))return new WP_Error('prstudio_loyalty_user','user_id valido obbligatorio.',array('status'=>400));$mode=sanitize_key((string)self::v($p,'mode','get'));$before=(int)get_user_meta($uid,'_prstudio_loyalty_points',true);if('get'===$mode)return self::read_result(array('user_id'=>$uid,'points'=>$before,'tier'=>(string)get_user_meta($uid,'_prstudio_loyalty_tier',true)),'user_meta');$points='set'===$mode?(int)self::v($p,'points',$before):$before+(int)self::v($p,'points',self::v($p,'delta',0));update_user_meta($uid,'_prstudio_loyalty_points',$points);if(isset($p['tier']))update_user_meta($uid,'_prstudio_loyalty_tier',sanitize_key((string)$p['tier']));$after=(int)get_user_meta($uid,'_prstudio_loyalty_points',true);return self::write_result(array('user_id'=>$uid,'before'=>$before,'points'=>$after,'tier'=>(string)get_user_meta($uid,'_prstudio_loyalty_tier',true)),$after===$points,'loyalty_readback');}
	private static function customer360(array $p){$uid=absint(self::v($p,'user_id',0));$email=sanitize_email((string)self::v($p,'email',''));$u=$uid?get_user_by('id',$uid):($email?get_user_by('email',$email):false);if(!$u)return new WP_Error('prstudio_customer_required','user_id o email esistente obbligatorio.',array('status'=>400));$orders=self::customer_orders($u->ID,self::limit($p,100,200));$spent=0;$last=null;foreach($orders as $o){$spent+=(float)$o->get_total();$d=$o->get_date_created();if($d&&(!$last||$d->getTimestamp()>$last))$last=$d->getTimestamp();}return self::read_result(array('user'=>array('id'=>$u->ID,'email'=>$u->user_email,'display_name'=>$u->display_name,'roles'=>$u->roles),'orders'=>count($orders),'lifetime_value'=>$spent,'last_order_at'=>$last?gmdate(DATE_ATOM,$last):null,'loyalty_points'=>(int)get_user_meta($u->ID,'_prstudio_loyalty_points',true)),'wordpress_woocommerce_aggregation');}
	private static function cookie_consent(array $p){$record=array('enabled'=>(bool)self::v($p,'enabled',true),'message'=>sanitize_text_field((string)self::v($p,'message','Questo sito utilizza cookie secondo la propria informativa.')),'policy_url'=>esc_url_raw((string)self::v($p,'policy_url',get_privacy_policy_url())),'updated_at'=>gmdate(DATE_ATOM));$ok=self::set_state('legal','cookie_consent',$record);return self::write_result($record,$ok&&self::get_state('legal','cookie_consent')===$record,'cookie_consent_readback');}
	public static function handle_cookie_consent(): void {
		if ( 'POST' !== strtoupper( (string) ( $_SERVER['REQUEST_METHOD'] ?? '' ) ) || empty( $_POST['prstudio_cookie_accept'] ) ) { return; }
		$nonce = sanitize_text_field( wp_unslash( (string) ( $_POST['_prstudio_cookie_nonce'] ?? '' ) ) );
		if ( ! wp_verify_nonce( $nonce, 'prstudio_cookie_accept' ) ) { return; }
		setcookie( 'prstudio_cookie_consent', '1', array( 'expires' => time() + YEAR_IN_SECONDS, 'path' => COOKIEPATH ?: '/', 'domain' => COOKIE_DOMAIN ?: '', 'secure' => is_ssl(), 'httponly' => true, 'samesite' => 'Lax' ) );
		$_COOKIE['prstudio_cookie_consent'] = '1';
		$target = wp_get_referer();
		wp_safe_redirect( $target ? $target : home_url( '/' ) );
		exit;
	}
	public static function render_cookie_consent(): void {
		$c = self::get_state( 'legal', 'cookie_consent' );
		if ( ! is_array( $c ) || empty( $c['enabled'] ) || ! empty( $_COOKIE['prstudio_cookie_consent'] ) ) { return; }
		echo '<div id="prstudio-cookie-consent" role="region" aria-label="Cookie" style="position:fixed;z-index:2147483000;left:1rem;right:1rem;bottom:1rem;padding:1rem;background:#111;color:#fff">' . esc_html( (string) $c['message'] ) . ' ';
		if ( ! empty( $c['policy_url'] ) ) { echo '<a style="color:#fff;text-decoration:underline" href="' . esc_url( $c['policy_url'] ) . '">Privacy</a> '; }
		echo '<form method="post" style="display:inline"><input type="hidden" name="prstudio_cookie_accept" value="1"><input type="hidden" name="_prstudio_cookie_nonce" value="' . esc_attr( wp_create_nonce( 'prstudio_cookie_accept' ) ) . '"><button type="submit">OK</button></form></div>';
	}
	private static function policy_page(array $p,string $kind){$id=absint(self::v($p,'post_id',0));if('privacy'===$kind&&!$id)$id=(int)get_option('wp_page_for_privacy_policy');$title=sanitize_text_field((string)self::v($p,'title',$kind==='privacy'?'Privacy Policy':'Termini e Condizioni'));$content=(string)self::v($p,'content','');if(!$content)return new WP_Error('prstudio_policy_content','content obbligatorio; PR STUDIO non inventa testo legale.',array('status'=>400));$content=wp_kses_post($content);$data=array('post_type'=>'page','post_status'=>sanitize_key((string)self::v($p,'status','draft')),'post_title'=>$title,'post_content'=>$content);if($id)$data['ID']=$id;$r=$id?wp_update_post(wp_slash($data),true):wp_insert_post(wp_slash($data),true);if(is_wp_error($r))return $r;$id=(int)$r;if('privacy'===$kind)update_option('wp_page_for_privacy_policy',$id);$after=get_post($id);return self::write_result(array('post_id'=>$id,'kind'=>$kind,'status'=>$after?$after->post_status:null,'url'=>get_permalink($id)),(bool)$after&&$after->post_content===$content,'policy_page_readback');}
	private static function privacy_request(array $p){if(!function_exists('wp_create_user_request'))return new WP_Error('prstudio_privacy_api_required','WordPress privacy request API non disponibile.',array('status'=>503));$email=sanitize_email((string)self::v($p,'email',''));$type=sanitize_key((string)self::v($p,'type','export_personal_data'));if(!$email||!in_array($type,array('export_personal_data','remove_personal_data'),true))return new WP_Error('prstudio_privacy_args','email e type export_personal_data/remove_personal_data obbligatori.',array('status'=>400));$id=wp_create_user_request($email,$type);if(is_wp_error($id))return $id;$post=get_post($id);return self::write_result(array('request_id'=>$id,'email'=>$email,'type'=>$type,'status'=>$post?$post->post_status:null),(bool)$post,'privacy_request_readback');}
	private static function state_record( string $section, array $p, string $idkey ) {
		$operation = sanitize_key( (string) self::v( $p, 'operation', 'upsert' ) );
		$records = self::get_state( $section ); $records = is_array( $records ) ? $records : array();
		$id = sanitize_key( (string) self::v( $p, $idkey, self::v( $p, 'id', '' ) ) );
		if ( 'list' === $operation ) { return self::read_result( array( 'items' => array_values( $records ), 'count' => count( $records ), 'section' => $section ), 'state_collection_readback' ); }
		if ( 'get' === $operation ) { if ( ! $id || ! isset( $records[ $id ] ) ) { return new WP_Error( 'prstudio_state_record_missing', 'Record non trovato.', array( 'status' => 404, 'section' => $section, $idkey => $id ) ); } return self::read_result( array( $idkey => $id, 'record' => $records[ $id ] ), 'state_record_readback' ); }
		if ( 'delete' === $operation ) {
			if ( ! $id || ! isset( $records[ $id ] ) ) { return new WP_Error( 'prstudio_state_record_missing', 'Record non trovato.', array( 'status' => 404, 'section' => $section, $idkey => $id ) ); }
			$state = self::state(); unset( $state[ $section ][ $id ] ); if ( empty( $state[ $section ] ) ) { $state[ $section ] = array(); } $ok = self::save_state( $state ); $after = self::get_state( $section, $id );
			return self::write_result( array( $idkey => $id, 'deleted' => true, 'section' => $section ), $ok && null === $after, 'state_delete_readback' );
		}
		if ( 'transition' === $operation ) {
			if ( ! $id || ! isset( $records[ $id ] ) ) { return new WP_Error( 'prstudio_state_record_missing', 'Record non trovato per la transizione.', array( 'status' => 404, 'section' => $section, $idkey => $id ) ); }
			$status = sanitize_key( (string) self::v( $p, 'status', '' ) ); if ( ! $status ) { return new WP_Error( 'prstudio_state_status_required', 'status è obbligatorio per transition.', array( 'status' => 400 ) ); }
			$record = $records[ $id ]; $record['status'] = $status; $record['updated_at'] = gmdate( DATE_ATOM ); $record['history'] = is_array( $record['history'] ?? null ) ? $record['history'] : array(); $record['history'][] = array( 'status' => $status, 'at' => $record['updated_at'], 'note' => sanitize_text_field( (string) self::v( $p, 'note', '' ) ) );
			$ok = self::set_state( $section, $id, $record ); return self::write_result( array( $idkey => $id, 'record' => $record ), $ok && self::get_state( $section, $id ) === $record, 'state_transition_readback' );
		}
		if ( ! in_array( $operation, array( 'upsert','set' ), true ) ) { return new WP_Error( 'prstudio_state_operation_invalid', 'Operazione lifecycle non valida.', array( 'status' => 400, 'operation' => $operation, 'section' => $section ) ); }
		if ( ! $id ) { $id = sanitize_key( $section . '-' . substr( wp_generate_uuid4(), 0, 12 ) ); }
		$current = is_array( $records[ $id ] ?? null ) ? $records[ $id ] : array(); $data = self::redact_sensitive( $p ); unset( $data['operation'], $data[ $idkey ], $data['id'] );
		$record = array_replace( $current, array( 'id' => $id, 'data' => array_replace( is_array( $current['data'] ?? null ) ? $current['data'] : array(), $data ), 'status' => sanitize_key( (string) self::v( $p, 'status', $current['status'] ?? 'active' ) ), 'created_at' => $current['created_at'] ?? gmdate( DATE_ATOM ), 'updated_at' => gmdate( DATE_ATOM ) ) );
		$ok = self::set_state( $section, $id, $record ); return self::write_result( array( $idkey => $id, 'record' => $record, 'lifecycle_operations' => array( 'list','get','upsert','transition','delete' ) ), $ok && self::get_state( $section, $id ) === $record, 'state_lifecycle_readback' );
	}
	private static function keyword_monitor(array $p,string $kind){$keywords=array_values(array_filter(array_map('sanitize_text_field',(array)self::v($p,'keywords',array()))));if(!$keywords)return new WP_Error('prstudio_keywords_required','keywords obbligatorio.',array('status'=>400));$f=self::fetch_sources($p);if(isset($f['error']))return $f['error'];$hits=[];foreach($f['items'] as $i){$text=mb_strtolower(self::text_from_html((string)($i['body']??'')));$found=[];foreach($keywords as $kw)if(str_contains($text,mb_strtolower($kw)))$found[]=$kw;$hits[]=array('url'=>$i['url'],'status'=>$i['status']??0,'keywords'=>$found,'match_count'=>count($found));}return self::read_result(array('kind'=>$kind,'keywords'=>$keywords,'sources'=>$hits),'bounded_source_keyword_scan');}
	private static function compliance(array $p){$issues=[];$privacy=(int)get_option('wp_page_for_privacy_policy');if(!$privacy||!get_post($privacy))$issues[]='privacy_policy_missing';if(!is_ssl())$issues[]='https_not_detected';$consent=self::get_state('legal','cookie_consent');if(!is_array($consent)||empty($consent['enabled']))$issues[]='managed_cookie_consent_not_enabled';$admin=get_option('admin_email');if(!is_email($admin))$issues[]='admin_email_invalid';return self::read_result(array('issues'=>$issues,'passed'=>!$issues,'scope'=>'technical_configuration_check_not_legal_advice','requested_framework'=>sanitize_text_field((string)self::v($p,'framework','general'))),'wordpress_compliance_checks');}
	private static function waf(array $p){$mode=sanitize_key((string)self::v($p,'mode','list'));$rules=(array)self::get_state('security','waf_rules');if('list'===$mode)return self::read_result(array('rules'=>$rules,'count'=>count($rules)),'waf_state');$id=sanitize_key((string)self::v($p,'rule_id',''));if('remove'===$mode){if(!$id||!isset($rules[$id]))return new WP_Error('prstudio_waf_rule_not_found','rule_id non trovato.',array('status'=>404));unset($rules[$id]);$ok=self::set_state('security','waf_rules',$rules);return self::write_result(array('removed'=>$id,'remaining'=>count($rules)),$ok&&!isset(((array)self::get_state('security','waf_rules'))[$id]),'waf_readback');}if(!$id)$id='rule-'.substr(wp_generate_uuid4(),0,10);$kind=sanitize_key((string)self::v($p,'kind','ip'));$value=sanitize_text_field((string)self::v($p,'value',''));if(!$value||!in_array($kind,array('ip','path','user_agent'),true))return new WP_Error('prstudio_waf_rule_args','kind ip/path/user_agent e value obbligatori.',array('status'=>400));$rules[$id]=array('id'=>$id,'kind'=>$kind,'value'=>$value,'enabled'=>(bool)self::v($p,'enabled',true));$ok=self::set_state('security','waf_rules',$rules);return self::write_result(array('rule'=>$rules[$id]),$ok,'waf_readback');}
	public static function enforce_waf_rules(): void {$rules=(array)self::get_state('security','waf_rules');if(!$rules)return;$ip=(string)($_SERVER['REMOTE_ADDR']??'');$uri=(string)($_SERVER['REQUEST_URI']??'');$ua=(string)($_SERVER['HTTP_USER_AGENT']??'');foreach($rules as $r){if(empty($r['enabled']))continue;$match=('ip'===($r['kind']??'')&&hash_equals((string)$r['value'],$ip))||('path'===($r['kind']??'')&&str_contains($uri,(string)$r['value']))||('user_agent'===($r['kind']??'')&&false!==stripos($ua,(string)$r['value']));if($match){status_header(403);nocache_headers();exit('Forbidden');}}}
	private static function ssl(array $p){$host=sanitize_text_field((string)self::v($p,'host',wp_parse_url(home_url(),PHP_URL_HOST)));$port=absint(self::v($p,'port',443));$mode=sanitize_key((string)self::v($p,'mode','inspect'));if('inspect'!==$mode)return self::external_provider('ssl_cert_manage',$p);if(!$host)return new WP_Error('prstudio_ssl_host','host obbligatorio.',array('status'=>400));$ctx=stream_context_create(array('ssl'=>array('capture_peer_cert'=>true,'verify_peer'=>true,'verify_peer_name'=>true,'peer_name'=>$host,'SNI_enabled'=>true)));$errno=0;$err='';$fp=@stream_socket_client('ssl://'.$host.':'.$port,$errno,$err,8,STREAM_CLIENT_CONNECT,$ctx);if(!$fp)return new WP_Error('prstudio_ssl_connect','Connessione TLS fallita: '.$err,array('status'=>502,'errno'=>$errno));$params=stream_context_get_params($fp);fclose($fp);$cert=$params['options']['ssl']['peer_certificate']??null;if(!$cert||!function_exists('openssl_x509_parse'))return new WP_Error('prstudio_ssl_parse','Certificato non analizzabile.',array('status'=>500));$x=openssl_x509_parse($cert);return self::read_result(array('host'=>$host,'subject'=>$x['subject']??array(),'issuer'=>$x['issuer']??array(),'valid_from'=>isset($x['validFrom_time_t'])?gmdate(DATE_ATOM,$x['validFrom_time_t']):null,'valid_to'=>isset($x['validTo_time_t'])?gmdate(DATE_ATOM,$x['validTo_time_t']):null,'days_remaining'=>isset($x['validTo_time_t'])?(int)floor(($x['validTo_time_t']-time())/86400):null),'live_tls_certificate');}
	private static function disaster_recovery(array $p){if(!empty($p['checkpoint_id']))return WPAIB_REST::execute_control_action('/maintenance-manage','restore_release_checkpoint',array('checkpoint_id'=>(string)$p['checkpoint_id']),'agency_semantic');if(has_filter('prstudio_enterprise_provider_execute_disaster_recovery_failover'))return self::external_provider('disaster_recovery_failover',$p);return new WP_Error('prstudio_dr_precondition','checkpoint_id locale oppure provider failover registrato obbligatorio.',array('status'=>400));}
	private static function load_test(array $p){$url=esc_url_raw((string)self::v($p,'url',home_url('/')));$requests=max(1,min(20,absint(self::v($p,'requests',5))));$times=[];$codes=[];for($i=0;$i<$requests;$i++){$t=microtime(true);$r=wp_safe_remote_get($url,array('timeout'=>10,'redirection'=>2,'limit_response_size'=>65536,'user-agent'=>'PR-STUDIO-LoadTest/1.0.0'));$times[]=microtime(true)-$t;$codes[]=is_wp_error($r)?0:wp_remote_retrieve_response_code($r);}return self::read_result(array('url'=>$url,'requests'=>$requests,'codes'=>$codes,'avg_ms'=>round(array_sum($times)/count($times)*1000,2),'max_ms'=>round(max($times)*1000,2),'bounded'=>true,'concurrency'=>1),'bounded_http_probe');}
	private static function warehouse_export(array $p){
		$mode=sanitize_key((string)self::v($p,'mode','sync'));if(!in_array($mode,array('sync','export'),true))return new WP_Error('prstudio_warehouse_mode_invalid','mode deve essere sync oppure export.',array('status'=>400));
		if('sync'===$mode&&!has_filter('prstudio_enterprise_provider_execute_data_warehouse_sync'))return new WP_Error('prstudio_warehouse_provider_required','La sincronizzazione verso un data warehouse richiede un provider reale già configurato. Usare mode=export per un export locale verificato.',array('status'=>503,'adapter_hook'=>'prstudio_enterprise_provider_execute_data_warehouse_sync'));
		$ok=self::require_wc();if(is_wp_error($ok))return $ok;$orders=function_exists('wc_get_orders')?wc_get_orders(array('limit'=>self::limit($p,100,100),'return'=>'objects','status'=>array_keys(wc_get_order_statuses()))):array();$rows=[];foreach($orders as $o)$rows[]=array('order_id'=>$o->get_id(),'status'=>$o->get_status(),'currency'=>$o->get_currency(),'total'=>(float)$o->get_total(),'customer_id'=>$o->get_customer_id(),'created_at'=>$o->get_date_created()?$o->get_date_created()->date(DATE_ATOM):null);$f=self::uploads_file('data-warehouse-'.gmdate('Ymd-His').'.json');if(isset($f['error']))return new WP_Error('prstudio_warehouse_path',$f['error'],array('status'=>500));$written=false!==file_put_contents($f['path'],wp_json_encode($rows,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX);$hash=$written&&is_file($f['path'])?hash_file('sha256',$f['path']):false;if(!$hash)return new WP_Error('prstudio_warehouse_export_failed','Export data warehouse non verificabile.',array('status'=>500));
		if('sync'===$mode){$ext=self::external_provider('data_warehouse_sync',array_merge($p,array('local_export_path'=>$f['path'],'local_export_sha256'=>$hash)));if(is_wp_error($ext))return $ext;return $ext;}
		return self::write_result(array('mode'=>'export','rows'=>count($rows),'path'=>$f['path'],'url'=>$f['url'],'sha256'=>$hash,'external_sync'=>false),true,'warehouse_export_hash');
	}

	private static function recommendation_train(array $p){$ok=self::require_wc();if(is_wp_error($ok))return $ok;$orders=wc_get_orders(array('limit'=>self::limit($p,200,500),'status'=>array('wc-completed','wc-processing')));$pairs=[];foreach($orders as $o){$ids=[];foreach($o->get_items() as $item){$id=$item->get_product_id();if($id)$ids[]=$id;}$ids=array_values(array_unique($ids));for($i=0;$i<count($ids);$i++)for($j=0;$j<count($ids);$j++)if($i!==$j)$pairs[$ids[$i]][$ids[$j]]=($pairs[$ids[$i]][$ids[$j]]??0)+1;}foreach($pairs as &$m)arsort($m);unset($m);$model=array('trained_at'=>gmdate(DATE_ATOM),'orders'=>count($orders),'pairs'=>$pairs);$stored=self::set_state('recommendation','model',$model);return self::write_result(array('orders'=>count($orders),'products'=>count($pairs),'model_version'=>$model['trained_at']),$stored,'recommendation_model_readback');}
	private static function recommendation_serve(array $p){$id=absint(self::v($p,'product_id',self::v($p,'id',0)));$model=self::get_state('recommendation','model');if(!is_array($model)||empty($model['pairs']))return new WP_Error('prstudio_recommendation_model_required','Eseguire recommendation_engine_train prima del serve.',array('status'=>409));$map=(array)($model['pairs'][$id]??array());$out=[];foreach(array_slice($map,0,self::limit($p,5,20),true) as $pid=>$score)$out[]=array('product_id'=>(int)$pid,'score'=>$score,'name'=>get_the_title((int)$pid),'url'=>get_permalink((int)$pid));return self::read_result(array('product_id'=>$id,'recommendations'=>$out,'trained_at'=>$model['trained_at']??null),'stored_cooccurrence_model');}
	private static function ab_create(array $p){
		$id=sanitize_key((string)self::v($p,'experiment_id',''));if(!$id)$id='ab-'.substr(wp_generate_uuid4(),0,12);
		$raw=(array)self::v($p,'variants',array());if(count($raw)<2)return new WP_Error('prstudio_ab_variants','Sono richieste almeno due variants.',array('status'=>400));
		$host=(string)wp_parse_url(home_url('/'),PHP_URL_HOST);$variants=[];$seen=[];$i=0;
		foreach(array_slice($raw,0,10) as $v){if(!is_array($v))continue;$url=esc_url_raw((string)($v['url']??''));$vh=(string)wp_parse_url($url,PHP_URL_HOST);$path=(string)wp_parse_url($url,PHP_URL_PATH);if(!$url||!$vh||strcasecmp($vh,$host)!==0)continue;$key=sanitize_key((string)($v['key']??$v['name']??('v'.(++$i))));if(!$key||isset($seen[$key]))continue;$weight=max(1,min(10000,(int)($v['weight']??1)));$variants[]=array('key'=>$key,'name'=>sanitize_text_field((string)($v['name']??$key)),'url'=>$url,'path'=>$path?:'/','weight'=>$weight);$seen[$key]=true;}
		if(count($variants)<2)return new WP_Error('prstudio_ab_variants_invalid','Sono richieste almeno due variants same-origin valide e univoche.',array('status'=>400));
		$status=sanitize_key((string)self::v($p,'status','draft'));if(!in_array($status,array('draft','active','paused','completed'),true))return new WP_Error('prstudio_ab_status_invalid','status deve essere draft, active, paused o completed.',array('status'=>400));
		$target=(string)self::v($p,'target_path','');if($target){$target=(string)wp_parse_url(home_url('/'.ltrim($target,'/')),PHP_URL_PATH);}if('active'===$status&&!$target)return new WP_Error('prstudio_ab_target_required','target_path è obbligatorio per un esperimento active.',array('status'=>400));foreach($variants as $v)if($target&&$v['path']===$target)return new WP_Error('prstudio_ab_redirect_loop','Una variant non può coincidere con target_path: produrrebbe un redirect loop.',array('status'=>400,'variant'=>$v['key']));
		$previous=self::get_state('ab_tests',$id);$stats=is_array($previous)&&is_array($previous['stats']??null)?$previous['stats']:array('exposures'=>array(),'conversions'=>array());foreach($variants as $v){$stats['exposures'][$v['key']]=(int)($stats['exposures'][$v['key']]??0);$stats['conversions'][$v['key']]=(int)($stats['conversions'][$v['key']]??0);}
		$record=array('id'=>$id,'name'=>sanitize_text_field((string)self::v($p,'name',$id)),'target_path'=>$target,'variants'=>$variants,'metric'=>sanitize_key((string)self::v($p,'metric','conversion')),'conversion_query_param'=>sanitize_key((string)self::v($p,'conversion_query_param','prstudio_ab_conversion')),'status'=>$status,'stats'=>$stats,'runtime_router_active'=>true,'created_at'=>is_array($previous)?($previous['created_at']??gmdate(DATE_ATOM)):gmdate(DATE_ATOM),'updated_at'=>gmdate(DATE_ATOM));$ok=self::set_state('ab_tests',$id,$record);$after=self::get_state('ab_tests',$id);return self::write_result(array('experiment'=>$after),$ok&&$after===$record,'ab_runtime_state_readback');
	}
	private static function ab_status(array $p){$id=sanitize_key((string)self::v($p,'experiment_id',self::v($p,'id','')));$r=$id?self::get_state('ab_tests',$id):null;if(!$r)return new WP_Error('prstudio_ab_not_found','experiment_id non trovato.',array('status'=>404));$stats=(array)($r['stats']??array());$rates=[];foreach((array)($r['variants']??array()) as $v){$key=(string)($v['key']??'');$e=(int)($stats['exposures'][$key]??0);$c=(int)($stats['conversions'][$key]??0);$rates[$key]=array('exposures'=>$e,'conversions'=>$c,'conversion_rate'=>$e>0?$c/$e:0.0);}return self::read_result(array('experiment'=>$r,'variant_metrics'=>$rates),'ab_runtime_state');}
	public static function apply_ab_tests(): void {
		if(is_admin()||defined('REST_REQUEST')&&REST_REQUEST||!in_array(strtoupper((string)($_SERVER['REQUEST_METHOD']??'GET')),array('GET','HEAD'),true))return;$tests=(array)self::get_state('ab_tests');if(!$tests)return;$request_path=(string)wp_parse_url((string)($_SERVER['REQUEST_URI']??'/'),PHP_URL_PATH);$host=(string)wp_parse_url(home_url('/'),PHP_URL_HOST);
		foreach($tests as $id=>$test){if(!is_array($test)||'active'!==($test['status']??''))continue;$variants=(array)($test['variants']??array());if(count($variants)<2)continue;$cookie='prstudio_ab_'.substr(hash('sha256',(string)$id),0,16);$assigned=sanitize_key((string)($_COOKIE[$cookie]??''));$variant=null;foreach($variants as $v)if(($v['key']??'')===$assigned){$variant=$v;break;}
			$conv_param=sanitize_key((string)($test['conversion_query_param']??'prstudio_ab_conversion'));if($assigned&&isset($_GET[$conv_param])&&sanitize_key((string)wp_unslash($_GET[$conv_param]))===sanitize_key((string)$id)){$conv_cookie=$cookie.'_conv';if(empty($_COOKIE[$conv_cookie])){$test['stats']['conversions'][$assigned]=(int)($test['stats']['conversions'][$assigned]??0)+1;self::set_state('ab_tests',(string)$id,$test);setcookie($conv_cookie,'1',array('expires'=>time()+30*DAY_IN_SECONDS,'path'=>'/','secure'=>is_ssl(),'httponly'=>true,'samesite'=>'Lax'));}}
			if(!$test['target_path']||$request_path!==$test['target_path'])continue;if(!$variant){$total=0;foreach($variants as $v)$total+=max(1,(int)($v['weight']??1));$pick=wp_rand(1,max(1,$total));$cursor=0;foreach($variants as $v){$cursor+=max(1,(int)($v['weight']??1));if($pick<=$cursor){$variant=$v;break;}}if(!$variant)$variant=$variants[0];$assigned=(string)$variant['key'];setcookie($cookie,$assigned,array('expires'=>time()+30*DAY_IN_SECONDS,'path'=>'/','secure'=>is_ssl(),'httponly'=>true,'samesite'=>'Lax'));$test['stats']['exposures'][$assigned]=(int)($test['stats']['exposures'][$assigned]??0)+1;self::set_state('ab_tests',(string)$id,$test);}
			$url=esc_url_raw((string)($variant['url']??''));if(!$url||strcasecmp((string)wp_parse_url($url,PHP_URL_HOST),$host)!==0)continue;$dest_path=(string)wp_parse_url($url,PHP_URL_PATH);if($dest_path===$request_path)continue;if(function_exists('add_query_arg'))$url=add_query_arg('prstudio_ab_variant',$assigned,$url);wp_safe_redirect($url,302,'PR STUDIO AB Test');exit;
		}
	}

	private static function cohort(array $p){$ok=self::require_wc();if(is_wp_error($ok))return $ok;$orders=wc_get_orders(array('limit'=>self::limit($p,500,1000),'status'=>array('wc-completed','wc-processing')));$by=[];foreach($orders as $o){$uid=$o->get_customer_id();if(!$uid)continue;$d=$o->get_date_created();if(!$d)continue;$month=$d->date('Y-m');if(!isset($by[$uid])||$month<$by[$uid]['first'])$by[$uid]=array('first'=>$month,'orders'=>0,'revenue'=>0);$by[$uid]['orders']++;$by[$uid]['revenue']+=(float)$o->get_total();}$coh=[];foreach($by as $r){$coh[$r['first']]['customers']=($coh[$r['first']]['customers']??0)+1;$coh[$r['first']]['orders']=($coh[$r['first']]['orders']??0)+$r['orders'];$coh[$r['first']]['revenue']=($coh[$r['first']]['revenue']??0)+$r['revenue'];}ksort($coh);return self::read_result(array('cohorts'=>$coh,'customers'=>count($by)),'woocommerce_order_cohorts');}
	private static function churn(array $p){$uid=absint(self::v($p,'user_id',0));if(!$uid)return new WP_Error('prstudio_churn_user','user_id obbligatorio.',array('status'=>400));$orders=self::customer_orders($uid,200);$last=$orders&&$orders[0]->get_date_created()?$orders[0]->get_date_created()->getTimestamp():null;$days=$last?(int)floor((time()-$last)/86400):null;$threshold=max(1,absint(self::v($p,'threshold_days',90)));$score=null===$days?1.0:min(1.0,$days/$threshold);return self::read_result(array('user_id'=>$uid,'last_order_at'=>$last?gmdate(DATE_ATOM,$last):null,'days_since_order'=>$days,'threshold_days'=>$threshold,'churn_score'=>round($score,3),'heuristic'=>true),'customer_order_recency');}
	private static function ltv(array $p){$uid=absint(self::v($p,'user_id',0));if(!$uid)return new WP_Error('prstudio_ltv_user','user_id obbligatorio.',array('status'=>400));$orders=self::customer_orders($uid,500);$sum=0;foreach($orders as $o)if(in_array($o->get_status(),array('completed','processing','on-hold'),true))$sum+=(float)$o->get_total();return self::read_result(array('user_id'=>$uid,'orders'=>count($orders),'ltv'=>$sum,'currency'=>function_exists('get_woocommerce_currency')?get_woocommerce_currency():'EUR'),'woocommerce_order_totals');}
	private static function attribution(array $p){$ok=self::require_wc();if(is_wp_error($ok))return $ok;$orders=wc_get_orders(array('limit'=>self::limit($p,500,1000),'status'=>array('wc-completed','wc-processing')));$by=[];foreach($orders as $o){$src=(string)($o->get_meta('_utm_source',true)?:$o->get_meta('_wc_order_attribution_utm_source',true)?:'direct');$by[$src]['orders']=($by[$src]['orders']??0)+1;$by[$src]['revenue']=($by[$src]['revenue']??0)+(float)$o->get_total();}return self::read_result(array('model'=>'last_recorded_source','channels'=>$by,'orders'=>count($orders)),'woocommerce_attribution_meta');}
	private static function roas(array $p){$spend=(float)self::v($p,'spend',0);$revenue=(float)self::v($p,'revenue',0);if($spend<=0)return new WP_Error('prstudio_roas_spend','spend > 0 obbligatorio.',array('status'=>400));return self::read_result(array('spend'=>$spend,'revenue'=>$revenue,'roas'=>$revenue/$spend,'currency'=>strtoupper(sanitize_text_field((string)self::v($p,'currency','EUR')))),'provided_financial_inputs');}
	private static function wholesale(array $p){
		if(!get_role('wholesale_customer'))add_role('wholesale_customer','Wholesale Customer',array('read'=>true));$discount=max(0.0,min(100.0,(float)self::v($p,'discount_percent',0)));$minimum=max(0.0,(float)self::v($p,'minimum_order',0));$record=array('enabled'=>(bool)self::v($p,'enabled',true),'discount_percent'=>$discount,'minimum_order'=>$minimum,'runtime_price_filter'=>true,'checkout_minimum_enforcement'=>true,'updated_at'=>gmdate(DATE_ATOM));$ok=self::set_state('commerce','wholesale',$record);$after=self::get_state('commerce','wholesale');return self::write_result($record,$ok&&null!==get_role('wholesale_customer')&&$after===$record,'role_state_and_runtime_hooks');
	}

	private static function partner_api(array $p){$endpoint=esc_url_raw((string)self::v($p,'endpoint',''));if(!$endpoint)return new WP_Error('prstudio_partner_endpoint','endpoint HTTPS obbligatorio.',array('status'=>400));if('https'!==wp_parse_url($endpoint,PHP_URL_SCHEME))return new WP_Error('prstudio_partner_https','Sono ammessi solo endpoint HTTPS.',array('status'=>400));$record=array('endpoint'=>$endpoint,'name'=>sanitize_text_field((string)self::v($p,'name','partner')),'auth_mode'=>sanitize_key((string)self::v($p,'auth_mode','request_only')),'secret_stored'=>false,'updated_at'=>gmdate(DATE_ATOM));$probe=wp_safe_remote_head($endpoint,array('timeout'=>5,'redirection'=>2,'user-agent'=>'PR-STUDIO/1.0.0'));$record['probe_status']=is_wp_error($probe)?0:wp_remote_retrieve_response_code($probe);$ok=self::set_state('partner_apis',sanitize_key($record['name']),$record);return self::write_result($record,$ok,'partner_config_readback');}
	private static function geo_redirect(array $p){$map=(array)self::v($p,'map',array());if(!$map)return new WP_Error('prstudio_geo_map','map paese=>URL obbligatoria.',array('status'=>400));$clean=[];foreach($map as $country=>$url){$c=strtoupper(preg_replace('/[^A-Z]/i','',(string)$country));$u=esc_url_raw((string)$url);if(strlen($c)===2&&$u)$clean[$c]=$u;}$record=array('enabled'=>(bool)self::v($p,'enabled',true),'map'=>$clean,'updated_at'=>gmdate(DATE_ATOM));$ok=self::set_state('international','geo_redirect',$record);return self::write_result($record,$ok,'geo_redirect_readback');}
	public static function apply_geo_redirect(): void {$cfg=self::get_state('international','geo_redirect');if(!is_array($cfg)||empty($cfg['enabled'])||empty($cfg['map'])||is_admin()||!empty($_COOKIE['prstudio_geo_redirected']))return;$country=strtoupper(sanitize_text_field((string)($_SERVER['HTTP_CF_IPCOUNTRY']??$_SERVER['GEOIP_COUNTRY_CODE']??'')));if(!$country||empty($cfg['map'][$country]))return;$target=esc_url_raw((string)$cfg['map'][$country]);if(!$target||wp_parse_url($target,PHP_URL_HOST)===wp_parse_url(home_url(),PHP_URL_HOST))return;setcookie('prstudio_geo_redirected','1',array('expires'=>time()+DAY_IN_SECONDS,'path'=>COOKIEPATH?:'/','domain'=>COOKIE_DOMAIN?:'','secure'=>is_ssl(),'httponly'=>true,'samesite'=>'Lax'));wp_safe_redirect($target,302,'PR STUDIO Geo Redirect');exit;}
	private static function duty(array $p){$value=(float)self::v($p,'customs_value',self::v($p,'value',0));$duty=(float)self::v($p,'duty_rate_percent',0);$vat=(float)self::v($p,'vat_rate_percent',0);$shipping=(float)self::v($p,'shipping',0);if($value<0||$duty<0||$vat<0)return new WP_Error('prstudio_duty_args','Valori/rate non validi.',array('status'=>400));$duty_amount=$value*$duty/100;$vat_base=$value+$shipping+$duty_amount;$vat_amount=$vat_base*$vat/100;return self::read_result(array('customs_value'=>$value,'shipping'=>$shipping,'duty_rate_percent'=>$duty,'duty_amount'=>$duty_amount,'vat_rate_percent'=>$vat,'vat_amount'=>$vat_amount,'landed_tax_total'=>$duty_amount+$vat_amount,'source'=>'provided_rates_not_legal_ruling'),'deterministic_duty_math');}
	private static function payment_method(array $p){$id=sanitize_key((string)self::v($p,'gateway_id',self::v($p,'id','')));if(!$id)return new WP_Error('prstudio_gateway_id','gateway_id obbligatorio.',array('status'=>400));if(!function_exists('WC'))return new WP_Error('prstudio_wc_required','WooCommerce richiesto.',array('status'=>503));$gateways=WC()->payment_gateways()?WC()->payment_gateways()->payment_gateways():array();if(!isset($gateways[$id]))return new WP_Error('prstudio_gateway_not_found','Gateway non installato.',array('status'=>404,'gateway_id'=>$id));$settings=(array)get_option('woocommerce_'.$id.'_settings',array());$settings['enabled']=(bool)self::v($p,'enabled',true)?'yes':'no';update_option('woocommerce_'.$id.'_settings',$settings,false);$after=(array)get_option('woocommerce_'.$id.'_settings',array());return self::write_result(array('gateway_id'=>$id,'enabled'=>$after['enabled']??null),($after['enabled']??null)===$settings['enabled'],'gateway_settings_readback');}
	private static function market_compliance(array $p){$country=strtoupper(sanitize_text_field((string)self::v($p,'country','')));$requirements=(array)self::v($p,'requirements',array());$evidence=(array)self::v($p,'evidence',array());if(!$country)return new WP_Error('prstudio_market_country','country obbligatorio.',array('status'=>400));$missing=[];foreach($requirements as $r){$k=sanitize_key((string)$r);if($k&&!array_key_exists($k,$evidence))$missing[]=$k;}return self::read_result(array('country'=>$country,'requirements'=>$requirements,'missing'=>$missing,'passed'=>!$missing,'scope'=>'caller_supplied_requirements_plus_site_evidence_not_legal_advice'),'market_requirement_matrix');}
	private static function press_release(array $p){
		$title=sanitize_text_field((string)self::v($p,'title',''));$content=wp_kses_post((string)self::v($p,'content',''));if(!$title||!$content)return new WP_Error('prstudio_press_release_content','title e content obbligatori.',array('status'=>400));
		$distribute=(bool)self::v($p,'distribute',true);if($distribute&&!has_filter('prstudio_enterprise_provider_execute_press_release_distribute'))return new WP_Error('prstudio_press_distribution_provider_required','La distribuzione esterna richiede un provider reale già registrato; nessuna bozza viene creata implicitamente quando il provider manca. Usare distribute=false per creare soltanto la release locale.',array('status'=>503,'adapter_hook'=>'prstudio_enterprise_provider_execute_press_release_distribute'));
		$post=wp_insert_post(wp_slash(array('post_type'=>'post','post_status'=>sanitize_key((string)self::v($p,'status','draft')),'post_title'=>$title,'post_content'=>$content)),true);if(is_wp_error($post))return $post;$published=get_post((int)$post);if(!$published)return self::write_result(array('post_id'=>(int)$post,'url'=>get_permalink((int)$post),'distributed'=>false,'local_only'=>true,'verification_warning'=>'press_release_post_unreadable'),false,'press_release_post_readback');
		if($distribute){$ext=self::external_provider('press_release_distribute',array_merge($p,array('post_id'=>(int)$post,'url'=>get_permalink((int)$post))));if(is_wp_error($ext))return $ext;return $ext;}
		return self::write_result(array('post_id'=>(int)$post,'url'=>get_permalink((int)$post),'distributed'=>false,'local_only'=>true),(bool)$published,'press_release_post_readback');
	}

	private static function review_monitor(array $p){$f=self::fetch_sources($p);if(isset($f['error']))return $f['error'];$items=[];$ratings=[];foreach($f['items'] as $i){$text=self::text_from_html((string)($i['body']??''),10000);$rating=null;if(preg_match('/(?:rating|valutazione)[^0-9]{0,20}([0-5](?:[\.,][0-9])?)/i',$text,$m))$rating=(float)str_replace(',','.',$m[1]);if(null!==$rating)$ratings[]=$rating;$items[]=array('url'=>$i['url'],'status'=>$i['status']??0,'rating'=>$rating,'snippet'=>mb_substr($text,0,500));}return self::read_result(array('items'=>$items,'ratings_found'=>count($ratings),'average'=>$ratings?array_sum($ratings)/count($ratings):null),'bounded_review_source_scan');}
	private static function crisis(array $p){$text=mb_strtolower(sanitize_textarea_field((string)self::v($p,'text','')));$keywords=(array)self::v($p,'keywords',array('truffa','frode','richiamo','pericolo','intossicazione','data breach','violazione dati','scam','fraud'));$source_hits=[];if(!empty($p['source_urls'])){$f=self::fetch_sources($p);if(isset($f['error']))return $f['error'];foreach($f['items'] as $i)$text.=' '.mb_strtolower(self::text_from_html((string)($i['body']??''),20000));}$hits=[];foreach($keywords as $k){$k=mb_strtolower(sanitize_text_field((string)$k));if($k&&str_contains($text,$k))$hits[]=$k;}$score=min(100,count($hits)*20);return self::read_result(array('hits'=>$hits,'score'=>$score,'severity'=>$score>=60?'high':($score>=20?'medium':'low'),'automated_heuristic'=>true),'keyword_risk_scan');}
	private static function reputation(array $p){$ratings=array_values(array_filter(array_map('floatval',(array)self::v($p,'ratings',array())),fn($v)=>$v>=0&&$v<=5));if(!$ratings&&!empty($p['source_urls'])){$r=self::review_monitor($p);if(is_wp_error($r))return $r;foreach($r['items'] as $i)if(null!==($i['rating']??null))$ratings[]=(float)$i['rating'];}if(!$ratings)return new WP_Error('prstudio_reputation_ratings','ratings oppure source_urls con rating rilevabile obbligatori.',array('status'=>400));$avg=array_sum($ratings)/count($ratings);return self::read_result(array('count'=>count($ratings),'average'=>round($avg,3),'score_100'=>round($avg/5*100,1)),'rating_aggregation');}
	private static function market_trends(array $p){$f=self::fetch_sources($p);if(isset($f['error']))return $f['error'];$stop=array_flip(array('della','delle','degli','sono','come','this','that','with','from','per','che','del','and','the','una','uno','gli','con','nel','nei'));$freq=[];$items=[];foreach($f['items'] as $i){$text=mb_strtolower(self::text_from_html((string)($i['body']??''),30000));preg_match_all('/\p{L}[\p{L}\p{N}-]{3,}/u',$text,$m);foreach($m[0] as $w)if(!isset($stop[$w]))$freq[$w]=($freq[$w]??0)+1;$items[]=array('url'=>$i['url'],'status'=>$i['status']??0,'bytes'=>$i['bytes']??0);}arsort($freq);$terms=array_slice($freq,0,self::limit($p,20,50),true);return self::read_result(array('sources'=>$items,'top_terms'=>$terms,'method'=>'bounded_public_source_term_frequency'),'market_source_analysis');}
}
