<?php
if ( ! defined( 'ABSPATH' ) && ! defined( 'PRSTUDIO_UC_TESTING' ) ) { exit; }
final class PRSTUDIO_UC_Product_Audit {
    private static function ids(array $args):array{$ids=array_values(array_unique(array_filter(array_map('intval',(array)($args['ids']??array())))));if(!empty($args['id']))array_unshift($ids,(int)$args['id']);if($ids)return array_slice(array_values(array_unique($ids)),0,500);return function_exists('get_posts')?array_map('intval',(array)get_posts(array('post_type'=>'product','post_status'=>'publish','fields'=>'ids','posts_per_page'=>500,'orderby'=>'ID','order'=>'ASC'))):array();}
    private static function fingerprint(int $id,$p):string{$parts=array('id'=>$id,'modified'=>function_exists('get_post_modified_time')?(string)get_post_modified_time('U',true,$id):'','name'=>$p->get_name(),'slug'=>$p->get_slug(),'status'=>$p->get_status(),'stock'=>$p->get_stock_quantity(),'stock_status'=>$p->get_stock_status(),'image'=>$p->get_image_id());foreach(array('rank_math_focus_keyword','rank_math_title','rank_math_description','rank_math_canonical_url','rank_math_robots') as $k){$v=function_exists('get_post_meta')?get_post_meta($id,$k,true):'';$parts[$k]=is_scalar($v)?(string)$v:$v;}return class_exists('PRSTUDIO_UC_Memory')?PRSTUDIO_UC_Memory::fingerprint($parts):hash('sha256',json_encode($parts));}
    private static function terms(int $id,string $tax):array{if(!function_exists('get_the_terms'))return array();$t=get_the_terms($id,$tax);if(!is_array($t))return array();return array_values(array_filter(array_map(static fn($x)=>is_object($x)?(string)$x->name:'',$t)));}
    private static function checks(int $id,$p,?array $frontend):array{
        $title=trim((string)$p->get_name());$slug=trim((string)$p->get_slug());$desc=trim((string)wp_strip_all_tags((string)$p->get_description()));$short=trim((string)wp_strip_all_tags((string)$p->get_short_description()));$image=(int)$p->get_image_id();$alt=$image&&function_exists('get_post_meta')?trim((string)get_post_meta($image,'_wp_attachment_image_alt',true)):'';$cats=self::terms($id,'product_cat');$brands=array_merge(self::terms($id,'product_brand'),self::terms($id,'pwb-brand'));$focus=function_exists('get_post_meta')?trim((string)get_post_meta($id,'rank_math_focus_keyword',true)):'';$metaTitle=function_exists('get_post_meta')?trim((string)get_post_meta($id,'rank_math_title',true)):'';$metaDesc=function_exists('get_post_meta')?trim((string)get_post_meta($id,'rank_math_description',true)):'';$canonical=function_exists('get_post_meta')?trim((string)get_post_meta($id,'rank_math_canonical_url',true)):'';$robots=function_exists('get_post_meta')?get_post_meta($id,'rank_math_robots',true):array();$robots=is_array($robots)?$robots:array($robots);$content=function_exists('get_post_field')?(string)get_post_field('post_content',$id):'';$linkCount=preg_match_all('/<a\b[^>]+href=/i',$content,$m);$indexable='publish'===(string)$p->get_status()&&!in_array('noindex',$robots,true);
        $checks=array(
          'title'=>array('ok'=>''!==$title,'evidence'=>array('length'=>strlen($title))), 'slug'=>array('ok'=>''!==$slug,'evidence'=>array('value'=>$slug)),
          'description'=>array('ok'=>''!==$desc,'evidence'=>array('length'=>strlen($desc))), 'short_description'=>array('ok'=>''!==$short,'evidence'=>array('length'=>strlen($short))),
          'category'=>array('ok'=>!empty($cats),'evidence'=>array('terms'=>$cats)), 'brand'=>array('ok'=>!empty($brands),'evidence'=>array('terms'=>$brands)),
          'image'=>array('ok'=>$image>0,'evidence'=>array('image_id'=>$image)), 'alt'=>array('ok'=>''!==$alt,'evidence'=>array('length'=>strlen($alt))),
          'schema'=>array('ok'=>null!==$frontend?(bool)($frontend['product_schema']??false):null,'evidence'=>array('source'=>null!==$frontend?'public_html_sample':'not_sampled')),
          'canonical'=>array('ok'=>''!==$canonical||(!empty($frontend['canonical'])),'evidence'=>array('meta'=>$canonical,'frontend'=>$frontend['canonical']??'')),
          'indexability'=>array('ok'=>$indexable,'evidence'=>array('status'=>$p->get_status(),'robots'=>$robots)),
          'internal_links'=>array('ok'=>$linkCount>0,'evidence'=>array('stored_content_links'=>$linkCount)), 'stock'=>array('ok'=>true,'evidence'=>array('quantity'=>$p->get_stock_quantity(),'status'=>$p->get_stock_status())),
          'frontend'=>array('ok'=>null!==$frontend?(bool)($frontend['verified']??false):null,'evidence'=>$frontend??array('sampled'=>false)),
          'meta_seo'=>array('ok'=>''!==$metaTitle&&''!==$metaDesc,'evidence'=>array('title_present'=>''!==$metaTitle,'description_present'=>''!==$metaDesc)),
          'focus_keyword'=>array('ok'=>''!==$focus,'evidence'=>array('present'=>''!==$focus)),
        );
        return array('checks'=>$checks,'title'=>$title,'description_hash'=>hash('sha256',strtolower(preg_replace('/\s+/',' ',$desc))),'title_hash'=>hash('sha256',strtolower($title)));
    }
    public static function execute(array $args){
        if(!function_exists('wc_get_product'))return new WP_Error('prstudio_woocommerce_unavailable','WooCommerce unavailable.',array('status'=>503));$force=!empty($args['force_reanalysis']);$items=array();$hashes=array();$reused=0;$fresh=0;
        $base=class_exists('PRSTUDIO_UC_SEO_Intelligence')?PRSTUDIO_UC_SEO_Intelligence::audit_product_seo($args):array('items'=>array(),'frontend_samples'=>array());if(is_wp_error($base))return $base;$front=array();foreach((array)($base['frontend_samples']??array()) as $s)$front[(int)($s['id']??0)]=(array)($s['result']??array());
        foreach(self::ids($args) as $id){$p=wc_get_product($id);if(!$p)continue;$fp=self::fingerprint($id,$p);if(!$force&&class_exists('PRSTUDIO_UC_Memory')&&PRSTUDIO_UC_Memory::can_reuse('product_audit_v3',(string)$id,$fp)){$c=PRSTUDIO_UC_Memory::lookup('product_audit_v3',(string)$id);$item=(array)($c['summary']['item']??array());if($item){$item['memory_reused']=true;$items[]=$item;$reused++;$hashes[$id]=array('title'=>$item['duplicate_content']['title_hash']??'','description'=>$item['duplicate_content']['description_hash']??'');continue;}}
            $c=self::checks($id,$p,$front[$id]??null);$issues=array();foreach($c['checks'] as $name=>$check){if(false===($check['ok']??null))$issues[]=$name;}$item=array('id'=>$id,'sku'=>(string)$p->get_sku(),'url'=>function_exists('get_permalink')?(string)get_permalink($id):'','checks'=>$c['checks'],'issues'=>$issues,'issue_count'=>count($issues),'duplicate_content'=>array('title_hash'=>$c['title_hash'],'description_hash'=>$c['description_hash'],'duplicate_title'=>false,'duplicate_description'=>false),'memory_reused'=>false,'verified_from'=>'woocommerce+wordpress+bounded_public_html');$items[]=$item;$hashes[$id]=array('title'=>$c['title_hash'],'description'=>$c['description_hash']);$fresh++;if(class_exists('PRSTUDIO_UC_Memory'))PRSTUDIO_UC_Memory::remember('product_audit_v3',(string)$id,$fp,array('item'=>$item,'status'=>'verified'),21600);
        }
        $titleGroups=array();$descGroups=array();foreach($hashes as $id=>$h){if($h['title'])$titleGroups[$h['title']][]=$id;if($h['description'])$descGroups[$h['description']][]=$id;}foreach($items as &$item){$id=(int)$item['id'];$th=$item['duplicate_content']['title_hash']??'';$dh=$item['duplicate_content']['description_hash']??'';$item['duplicate_content']['duplicate_title']=isset($titleGroups[$th])&&count($titleGroups[$th])>1;$item['duplicate_content']['duplicate_description']=isset($descGroups[$dh])&&count($descGroups[$dh])>1;$item['duplicate_content']['scope']='audited_products_only';}unset($item);
        return array('provider'=>'prstudio_product_audit_orchestrator_v4','read_only'=>true,'products'=>count($items),'items'=>$items,'memory'=>array('reused_count'=>$reused,'fresh_count'=>$fresh),'completeness'=>array('frontend_sampled'=>count($front),'browser_required'=>false,'ocr_required'=>false),'verified'=>true,'evidence_only'=>true);
    }
    public static function schema_audit(array $args){$r=self::execute($args);if(is_wp_error($r))return $r;$items=array();foreach((array)$r['items'] as $i)$items[]=array('id'=>$i['id'],'url'=>$i['url'],'schema'=>$i['checks']['schema'],'canonical'=>$i['checks']['canonical'],'frontend'=>$i['checks']['frontend']);return array('provider'=>'prstudio_product_schema_audit_v4','items'=>$items,'count'=>count($items),'verified'=>true,'memory'=>$r['memory']);}
}
