<?php
if ( ! defined( 'ABSPATH' ) && ! defined( 'PRSTUDIO_UC_TESTING' ) ) { exit; }

/** Structured problem-solving session store with optional official MCP sidecar. */
final class PRSTUDIO_UC_Sequential_Thinking {
    public const VERSION='1.0.0';
    private const STATE='sequential-thinking';
    private const MAX_SESSIONS=200;
    private const MAX_THOUGHTS=128;

    private static function defaults():array{return array('sessions'=>array(),'metrics'=>array('calls'=>0,'revisions'=>0,'branches'=>0));}
    private static function clean_text(string $v,int $max=12000):string{$v=trim($v);if(class_exists('PRSTUDIO_UC_Memory'))$v=(string)PRSTUDIO_UC_Memory::redact($v);return substr($v,0,$max);}
    private static function session_id(string $id):string{$id=preg_replace('/[^A-Za-z0-9._:-]+/','-',trim($id));return substr(trim((string)$id,'-.'),0,96);}

    /** MCP-compatible sequential_thinking tool; stores explicit structured notes, never hidden model chain-of-thought. */
    public static function think(array $args){
        $thought=self::clean_text((string)($args['thought']??''));if(''===$thought)return new WP_Error('sequential_thought_required','thought is required.',array('status'=>400));
        $number=max(1,min(self::MAX_THOUGHTS,(int)($args['thoughtNumber']??$args['thought_number']??1)));$total=max($number,min(self::MAX_THOUGHTS,(int)($args['totalThoughts']??$args['total_thoughts']??$number)));$next=(bool)($args['nextThoughtNeeded']??$args['next_thought_needed']??false);$revision=(bool)($args['isRevision']??$args['is_revision']??false);$revises=max(0,min(self::MAX_THOUGHTS,(int)($args['revisesThought']??$args['revises_thought']??0)));$branchFrom=max(0,min(self::MAX_THOUGHTS,(int)($args['branchFromThought']??$args['branch_from_thought']??0)));$branch=self::session_id((string)($args['branchId']??$args['branch_id']??''));$needsMore=(bool)($args['needsMoreThoughts']??$args['needs_more_thoughts']??false);$session=self::session_id((string)($args['session_id']??''));if(''===$session){$seed=function_exists('wp_generate_uuid4')?wp_generate_uuid4():(function_exists('random_bytes')?bin2hex(random_bytes(16)):uniqid('seq-',true));$session='seq-'.substr(hash('sha256',$seed.'|'.$thought),0,20);}
        $useSidecar=!empty($args['prefer_official_sidecar'])||!empty($args['prefer_sidecar']);$sidecar=null;if($useSidecar&&class_exists('PRSTUDIO_UC_MCP_Toolchain')&&method_exists('PRSTUDIO_UC_MCP_Toolchain','sequential_thinking')){$sidecar=PRSTUDIO_UC_MCP_Toolchain::sequential_thinking(array('thought'=>$thought,'nextThoughtNeeded'=>$next,'thoughtNumber'=>$number,'totalThoughts'=>$total,'isRevision'=>$revision,'revisesThought'=>$revises?:null,'branchFromThought'=>$branchFrom?:null,'branchId'=>$branch?:null,'needsMoreThoughts'=>$needsMore));}
        $payload=PRSTUDIO_UC_Agency_State::mutate(self::STATE,self::defaults(),static function(array &$state)use($session,$thought,$number,$total,$next,$revision,$revises,$branchFrom,$branch,$needsMore){$s=is_array($state['sessions'][$session]??null)?$state['sessions'][$session]:array('id'=>$session,'created_gmt'=>gmdate('c'),'thoughts'=>array(),'branches'=>array());$entry=array('thoughtNumber'=>$number,'totalThoughts'=>$total,'thought'=>$thought,'nextThoughtNeeded'=>$next,'isRevision'=>$revision,'revisesThought'=>$revises?:null,'branchFromThought'=>$branchFrom?:null,'branchId'=>$branch?:null,'needsMoreThoughts'=>$needsMore,'recorded_gmt'=>gmdate('c'));$s['thoughts'][(string)$number]=$entry;if($branch){$s['branches'][$branch]=array('from'=>$branchFrom,'last_thought'=>$number,'updated_gmt'=>gmdate('c'));}$s['last_thought_number']=$number;$s['total_thoughts']=$total;$s['next_thought_needed']=$next||$needsMore;$s['updated_gmt']=gmdate('c');$state['sessions'][$session]=$s;if(count($state['sessions'])>self::MAX_SESSIONS){uasort($state['sessions'],static fn($a,$b)=>strcmp((string)($b['updated_gmt']??''),(string)($a['updated_gmt']??'')));$state['sessions']=array_slice($state['sessions'],0,self::MAX_SESSIONS,true);}$state['metrics']['calls']=(int)($state['metrics']['calls']??0)+1;if($revision)$state['metrics']['revisions']=(int)($state['metrics']['revisions']??0)+1;if($branch)$state['metrics']['branches']=(int)($state['metrics']['branches']??0)+1;return array('session'=>$s,'entry'=>$entry);});
        if(!is_array($payload))return new WP_Error('sequential_state_unavailable','Unable to persist sequential thinking session.',array('status'=>503,'retryable'=>true));
        return array('ok'=>true,'session_id'=>$session,'thoughtNumber'=>$number,'totalThoughts'=>$total,'nextThoughtNeeded'=>$next||$needsMore,'branches'=>array_keys((array)($payload['session']['branches']??array())),'engine'=>is_wp_error($sidecar)||null===$sidecar?'native_structured_session':'official_mcp_sidecar+native_durable_session','official_sidecar'=>is_wp_error($sidecar)?array('ok'=>false,'error'=>$sidecar->get_error_code()):$sidecar,'hidden_chain_of_thought_stored'=>false,'version'=>self::VERSION,'component'=>'sequential_thinking','component_version'=>self::VERSION,'suite_version'=>defined('PRSTUDIO_UC_VERSION')?PRSTUDIO_UC_VERSION:'');
    }

    /** Read a bounded structured session for resumption or audit. */
    public static function session(array $args){$id=self::session_id((string)($args['session_id']??''));$state=PRSTUDIO_UC_Agency_State::read(self::STATE,self::defaults());$s=$state['sessions'][$id]??null;if(!is_array($s))return new WP_Error('sequential_session_not_found','Sequential session not found.',array('status'=>404));return array('ok'=>true,'session'=>$s,'version'=>self::VERSION,'component'=>'sequential_thinking','component_version'=>self::VERSION,'suite_version'=>defined('PRSTUDIO_UC_VERSION')?PRSTUDIO_UC_VERSION:'');}
    /** Report subsystem metrics without exposing session contents. */
    public static function status(array $args=array()):array{$state=PRSTUDIO_UC_Agency_State::read(self::STATE,self::defaults());return array('ok'=>true,'version'=>self::VERSION,'component'=>'sequential_thinking','component_version'=>self::VERSION,'suite_version'=>defined('PRSTUDIO_UC_VERSION')?PRSTUDIO_UC_VERSION:'','sessions'=>count((array)$state['sessions']),'metrics'=>$state['metrics'],'max_thoughts'=>self::MAX_THOUGHTS,'hidden_chain_of_thought_stored'=>false);}
}
