<?php
if ( ! defined( 'ABSPATH' ) && ! defined( 'PRSTUDIO_UC_TESTING' ) ) { exit; }
final class PRSTUDIO_UC_Graph_Engine {
    private static function graph_path():string{return class_exists('PRSTUDIO_UC_Memory')?PRSTUDIO_UC_Memory::site_dir().'/site-knowledge-graph.json':'';}
    private static function load_persisted():?array{
        $p=self::graph_path();if(''===$p||!is_readable($p))return null;$d=json_decode((string)file_get_contents($p),true);if(!is_array($d))return null;
        $nodes=array_values((array)($d['nodes']??array()));$edges=array_values((array)($d['edges']??array()));return array('nodes'=>$nodes,'edges'=>$edges,'updated_gmt'=>(string)($d['updated_gmt']??''));
    }
    private static function components(array $nodes,array $edges):array{
        $ids=array();foreach($nodes as $n){$u=(string)($n['url']??$n['id']??'');if($u)$ids[$u]=true;}$adj=array();foreach($edges as $e){$a=(string)($e['from']??$e['source']??'');$b=(string)($e['to']??$e['target']??'');if(isset($ids[$a])&&isset($ids[$b])){$adj[$a][$b]=true;$adj[$b][$a]=true;}}
        $seen=array();$components=array();foreach(array_keys($ids) as $start){if(isset($seen[$start]))continue;$q=array($start);$seen[$start]=true;$part=array();for($i=0;isset($q[$i]);$i++){ $u=$q[$i];$part[]=$u;foreach(array_keys((array)($adj[$u]??array())) as $v){if(!isset($seen[$v])){$seen[$v]=true;$q[]=$v;}}}$components[]=$part;}
        usort($components,static fn($a,$b)=>count($b)<=>count($a));return array('count'=>count($components),'isolated_component_count'=>count(array_filter($components,static fn($x)=>count($x)<=1)),'components'=>array_map(static fn($x)=>array('size'=>count($x),'sample'=>array_slice($x,0,25)),array_slice($components,0,100)));
    }
    private static function annotate(array $result,string $source,bool $reused):array{
        $result['source']=$source;$result['freshness']=array('retrieved_at'=>gmdate('c'),'memory_reused'=>$reused);$result['completeness']=empty($result['edges_truncated'])&&empty($result['runtime']['errors']);$result['coverage']=array('nodes'=>(int)($result['node_count']??count((array)($result['nodes']??array()))),'edges'=>(int)($result['edge_count']??count((array)($result['edges']??array()))),'runtime_pages'=>(int)($result['runtime']['pages_checked']??0));$result['evidence']=array('provider'=>$result['provider']??'prstudio_graph_engine_v4','graph_hash'=>hash('sha256',json_encode(array($result['nodes']??array(),$result['edges']??array()),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)));return $result;
    }
    public static function build(array $args){
        $force=!empty($args['force_reanalysis']);if(!$force&&class_exists('PRSTUDIO_UC_Memory')&&PRSTUDIO_UC_Memory::can_reuse('seo_graph','site')){$p=self::load_persisted();if($p){$nodes=$p['nodes'];$edges=$p['edges'];$r=array('provider'=>'prstudio_persisted_incremental_graph_v4','node_count'=>count($nodes),'edge_count'=>count($edges),'nodes'=>$nodes,'edges'=>$edges,'edges_truncated'=>false,'components'=>self::components($nodes,$edges),'runtime'=>array('pages_checked'=>0,'errors'=>0));return self::annotate($r,'persistent_knowledge_graph',true);}}
        if(!class_exists('PRSTUDIO_UC_Public_Crawl'))return new WP_Error('prstudio_graph_backend_missing','Graph backend unavailable.',array('status'=>503));$r=PRSTUDIO_UC_Public_Crawl::build_internal_link_graph($args);if(is_wp_error($r))return $r;$r['components']=self::components((array)($r['nodes']??array()),(array)($r['edges']??array()));$r=self::annotate($r,'wordpress_inventory+sitemap+server_html+navigation',false);if(class_exists('PRSTUDIO_UC_Memory')){PRSTUDIO_UC_Memory::remember('seo_graph','site',PRSTUDIO_UC_Memory::fingerprint($r['evidence']),array('status'=>'verified','nodes'=>$r['node_count'],'edges'=>$r['edge_count']),21600);}return $r;
    }
    private static function bfs(array $nodes,array $edges,string $root):array{
        $set=array();foreach($nodes as $n){$u=(string)($n['url']??$n['id']??'');if($u)$set[$u]=true;}$adj=array();foreach($edges as $e){$a=(string)($e['from']??$e['source']??'');$b=(string)($e['to']??$e['target']??'');if(isset($set[$a])&&isset($set[$b]))$adj[$a][$b]=true;}
        $depth=array_fill_keys(array_keys($set),null);if(array_key_exists($root,$depth)){$depth[$root]=0;$q=array($root);}else{$q=array();}
        for($i=0;isset($q[$i]);$i++){ $u=$q[$i];foreach(array_keys((array)($adj[$u]??array())) as $v){$d=$depth[$u]+1;if(null===$depth[$v]||$d<$depth[$v]){$depth[$v]=$d;$q[]=$v;}}}
        return $depth;
    }
    public static function analyze_graph(array $nodes,array $edges,string $root,int $deep_threshold=4):array{
        $root=rtrim($root,'/').'/';$depth=self::bfs($nodes,$edges,$root);if(!array_key_exists($root,$depth)){ $alt=rtrim($root,'/'); if(array_key_exists($alt,$depth)){ $root=$alt;$depth=self::bfs($nodes,$edges,$root); } }
        $threshold=max(1,min(20,$deep_threshold));$dist=array();$unreachable=array();$deep=array();$max=0;foreach($depth as $u=>$d){if(null===$d){$unreachable[]=$u;continue;}$dist[(string)$d]=($dist[(string)$d]??0)+1;$max=max($max,(int)$d);if($d>$threshold)$deep[]=array('url'=>$u,'depth'=>$d);}ksort($dist,SORT_NUMERIC);
        $in=array();foreach($nodes as $n){$u=(string)($n['url']??$n['id']??'');if($u)$in[$u]=0;}foreach($edges as $e){$t=(string)($e['to']??$e['target']??'');if(isset($in[$t]))$in[$t]++;}$orph=array();foreach($in as $u=>$n){if(rtrim($u,'/')!==rtrim($root,'/')&&0===$n)$orph[]=array('url'=>$u,'inbound'=>0);}
        return array('algorithm'=>'BFS','root_url'=>$root,'max_depth'=>$max,'depth_distribution'=>$dist,'unreachable_count'=>count($unreachable),'unreachable_pages'=>$unreachable,'overly_deep_count'=>count($deep),'overly_deep'=>$deep,'orphan_count'=>count($orph),'orphan_pages'=>$orph,'components'=>self::components($nodes,$edges));
    }
    public static function depth(array $args){$g=self::build($args);if(is_wp_error($g))return $g;$root=trim((string)($args['root_url']??(function_exists('home_url')?home_url('/'):'http://localhost/')));$root=rtrim($root,'/').'/';$depth=self::bfs((array)$g['nodes'],(array)$g['edges'],$root);if(!array_key_exists($root,$depth)&&function_exists('home_url')){$alt=rtrim((string)home_url('/'),'/');if(array_key_exists($alt,$depth)){$root=$alt;$depth=self::bfs((array)$g['nodes'],(array)$g['edges'],$root);}}
        $threshold=max(1,min(20,(int)($args['deep_threshold']??4)));$dist=array();$unreachable=array();$deep=array();$max=0;foreach($depth as $u=>$d){if(null===$d){$unreachable[]=$u;continue;}$dist[(string)$d]=($dist[(string)$d]??0)+1;$max=max($max,(int)$d);if($d>$threshold)$deep[]=array('url'=>$u,'depth'=>$d);}ksort($dist,SORT_NUMERIC);
        return array('source'=>$g['source'],'completeness'=>$g['completeness'],'coverage'=>$g['coverage'],'freshness'=>$g['freshness'],'evidence'=>$g['evidence'],'root_url'=>$root,'algorithm'=>'BFS','max_depth'=>$max,'depth_distribution'=>$dist,'unreachable_count'=>count($unreachable),'unreachable_pages'=>array_slice($unreachable,0,1000),'overly_deep_count'=>count($deep),'overly_deep'=>array_slice($deep,0,1000),'verified'=>(bool)$g['completeness']);}
    public static function orphans(array $args){$g=self::build($args);if(is_wp_error($g))return $g;$in=array();$nodes=array();foreach((array)$g['nodes'] as $n){$u=(string)($n['url']??$n['id']??'');if($u){$nodes[$u]=$n;$in[$u]=0;}}foreach((array)$g['edges'] as $e){$t=(string)($e['to']??$e['target']??'');if(isset($in[$t]))$in[$t]++;}$home=function_exists('home_url')?rtrim((string)home_url('/'),'/'):'';$orph=array();foreach($in as $u=>$n){if(rtrim($u,'/')!==$home&&0===$n)$orph[]=array('url'=>$u,'inbound'=>0,'node'=>$nodes[$u]);}$components=self::components((array)$g['nodes'],(array)$g['edges']);return array('source'=>$g['source'],'completeness'=>$g['completeness'],'coverage'=>$g['coverage'],'freshness'=>$g['freshness'],'evidence'=>$g['evidence'],'orphan_count'=>count($orph),'orphan_pages'=>array_slice($orph,0,1000),'components'=>$components,'verified'=>(bool)$g['completeness']);}
}
